In [59]:
import pandas as pd
import re
import collections

In [60]:
#df = pd.read_csv('/Users/prajwal/Desktop/Columbia/C4SR/tesseract lib/mn 1850/data/MN_1850_final_output_tesseract.csv')
#df = pd.read_csv('/Users/prajwal/Desktop/Columbia/C4SR/tesseract lib/bk 1850/address 2/bk_1850_address2_firstrun.csv')
df = pd.read_csv('/Users/prajwal/Desktop/Columbia/C4SR/tesseract lib/bk 1850/data/BK_1850_final_output_tesseract.csv')

In [61]:
df.columns

Index(['Unnamed: 0', 'Full Name', 'First Name', 'Last Name', 'Middle Name',
       'Widow-flag', 'Widow Of', 'Title', 'Occupation', 'Full Address',
       'H Status-flag', 'H Address', 'H House Number', 'H Street Name',
       'H City', 'Address 2', 'Address 2 House Number',
       'Address 2 Street Name', 'Address 2 City', 'Index', 'Full Entry'],
      dtype='object')

In [62]:
#df['Full Address']

In [63]:
"""
for a in range(0, len(df)):
    print(a)
    #df['Full Address'][a] = str(df['Full Address'][a]).replace('Ç','C')
    #df['Full Address'][a] = str(df['Full Address'][a]).replace('√','Y')
    df['Full Address'][a] = str(df['Full Address'][a]).replace('¬',' ')
    df['Full Address'][a] = str(df['Full Address'][a]).replace('•',' ')
    df['Full Address'][a] = str(df['Full Address'][a]).replace('¢','c')
    
    
    # bottom part also commented out
    
    for i in range(0, 10):
        df['Full Address'][a] = str(df['Full Address'][a]).replace('&&','&')
    """

"\nfor a in range(0, len(df)):\n    print(a)\n    #df['Full Address'][a] = str(df['Full Address'][a]).replace('Ç','C')\n    #df['Full Address'][a] = str(df['Full Address'][a]).replace('√','Y')\n    df['Full Address'][a] = str(df['Full Address'][a]).replace('¬',' ')\n    df['Full Address'][a] = str(df['Full Address'][a]).replace('•',' ')\n    df['Full Address'][a] = str(df['Full Address'][a]).replace('¢','c')\n    \n    \n    # bottom part also commented out\n    \n    for i in range(0, 10):\n        df['Full Address'][a] = str(df['Full Address'][a]).replace('&&','&')\n    "

In [64]:
for a in range(0, len(df)):
    if '.5' in str(df['Full Address'][a]):
        print(a)
        df.at[a, 'Full Address'] = df['Full Address'][a].replace('.5','')
    if ',' in str(df['Full Address'][a]):
        df.at[a, 'Full Address'] = df['Full Address'][a].replace(',','')
    if '.' in str(df['Full Address'][a]):
        df.at[a, 'Full Address'] = df['Full Address'][a].replace('.','')
    if '  ' in str(df['Full Address'][a]):
        df.at[a, 'Full Address'] = df['Full Address'][a].replace('  ',' ')

1714
1934
1958
2066
2380
2513
2539
3263
3341
3515
3722
3946
4036
4142
4189
4413
4612
5040
5163
5280
5317
5342
5516
5684
5965
6066
6132
6210
6391
6458
6468
6701
6705
6891
7012
7229
7314
7533
7546
8414
8487
8538
8611
8810
9019
9054
9193
9430
9574
9749
9792
9878
10085
10183
10331
10445
10484
10734
10803
11196
11199
11521
11547
11634
11695
11757
11794
11800
12422
12457
12575
12725
12748
12853
12939
13135
13260
13437
13689
13690
13711
13728
14243
14322
14496
14860
14936
14948
15277
15382
15407
15619
15674

In [65]:
temp_replace_specials = {}
for a in range(0, len(df)):
    temp_str = re.sub('[^A-Za-z0-9]', ' ', str(df['Full Address'][a]))
    temp_str = temp_str.replace('&  &', '&x', 100).replace(' & ', ' ', 100).replace('&x', '&', 100).replace('&  &', '&', 100).replace('  ', ' & ').replace('&  &', '&', 100).replace('  ', ' ', 100)
    temp_str = temp_str.replace('Yh', 'Y h', 100)
    temp_str = temp_str.replace('NYh', 'NY h', 100)
    temp_str = temp_str.replace(' b ', ' h ', 100)
    temp_str = temp_str.replace('YV', 'W', 100)
    temp_str = temp_str.replace('Ayn', ' Av n ', 100)
    temp_str = temp_str.replace('avn', ' Av n ', 100)
    temp_str = temp_str.replace('Avy', ' Av ', 100)
    temp_str = temp_str.replace('.', '', 100)
    #temp_str = temp_str.replace(',', '', 100)
    temp_str = temp_str.replace(',', '', 100)
    temp_str = temp_str.replace('  ', ' ', 100)
    
    for i in range(0, 10):
        try:
            if temp_str.index('h'+str(i))>=0:
                #print(a,i,'yes')
                temp_str = temp_str.replace('h'+str(i), 'h '+str(i), 100)
        except:
            pass
    temp_replace_specials[a] = temp_str

In [66]:
temp_replace_specials[6]

'25 Front & Court'

In [67]:
temp_replace_specials[451].split()

['Hoyt', 'n', 'Atlantic', '&', '&', 'h', '163', 'Frout']

In [68]:
#temp_replace_specials[435].split().index('&')

In [69]:
def hasNumbers(inputString):
    return any(char.isdigit() for char in inputString)

In [70]:
part_after_h = {}
part_before_h = {}
part_before_and = {}
part_after_and = {}

for a in range(0, len(df)):
    loc_of_h = -1
    loc_of_and = -1
    try:
        loc_of_h = temp_replace_specials[a].split().index('h')
    except:
        pass
    try:
        loc_of_and = temp_replace_specials[a].split().index('&')
    except:
        pass
    if loc_of_h >= 0:
        part_after_h[a] = ' '.join(temp_replace_specials[a].split()[loc_of_h+1:])
        part_before_h[a] = ' '.join(temp_replace_specials[a].split()[0:loc_of_h])
    
    if loc_of_h < 0 and loc_of_and >= 0:
        temp_part_before_and = ' '.join(temp_replace_specials[a].split()[0:loc_of_and])
        if hasNumbers(temp_part_before_and):
            part_before_and[a] = ' '.join(temp_replace_specials[a].split()[0:loc_of_and])
            part_after_and[a] = ' '.join(temp_replace_specials[a].split()[loc_of_and+1:])

In [71]:
part_before_and

{6: '25 Front',
 39: '176 York',
 82: '258',
 84: '217 Adams',
 101: '121 Hicks',
 141: '6 Kelsey',
 149: '43',
 152: '50 Middagh',
 160: '1 Tillary',
 163: '15 Prospect',
 192: '20 Douglass',
 200: '3d ay',
 252: '84 Hudson av',
 273: '25 Hicks',
 315: '125 Hudson av',
 333: '105 Front',
 360: '58 Hicks',
 362: '71 Hicks',
 387: '150 Joralemon',
 435: '90 Main',
 441: '14 James',
 497: '6 Glake',
 503: '102 Middagh',
 522: '61 State',
 533: '132 Nassau',
 535: '19 Union',
 540: 'gunner vu s N 127 Mudson av',
 570: '7',
 575: '5th av House 27thet n Sth av',
 613: '270 Fulton',
 644: '43 Atlantie',
 657: '182 Jay',
 666: '270 Washington',
 679: '36 Sackett',
 680: '270 Washington',
 696: '9 Front',
 715: '66 Hudson av',
 728: '1 Hloward',
 730: '30 Clinton',
 753: '4 Blake',
 802: '155 Jay',
 815: '155 Jay',
 818: '179 Concord',
 821: '82 Livingston',
 876: '137 Myrtle av',
 917: '189 York',
 921: '178 Washington',
 923: '3 Kelsey',
 957: '330 Atlantic',
 983: '2 Kels',
 984: '8 Boerum',
 985: '52 Willow',
 998: '129 Atlantic',
 1003: '10 Cortlandt N',
 1010: '16 Fulton N',
 1020: '102 Nassau c Ann N',
 1022: '3 Joralemon',
 1023: '44',
 1047: 'Witr3am Apothecaries Hall 206 Fulton',
 1048: '147',
 1050: '59 High',
 1051: 'House 15 Fulton',
 1061: '143 High',
 1095: '654 Atlantic',
 1155: '4 Howard Place Water',
 1203: '1 Hall',
 1237: '47 Butler',
 1240: '165 Hudson av',
 1253: '3d avb 15th and 16th st Go',
 1285: '68 Water N Y',
 1296: 'widow 18 Hartt',
 1299: '96 Carl',
 2029: '74',
 2070: '95 Pearl',
 2084: '86 Myrtle av Alderman 3d ward',
 2435: '47 Y',
 2498: '28 Main',
 2506: '3 Cottage row',
 2763: '131 Court n',
 2768: '21st n 4th av Gowanus',
 2787: '12',
 2937: '193 Bridge',
 3241: 'Amity n Willow constable 9th Ward',
 3470: '34 Hicks',
 3862: '8 Cottage row',
 3915: '43 Fulton hc Clinton',
 3916: '43 Fulton',
 4039: '157 Sands c Gold Alderman 7th ward',
 4723: '125',
 4731: 'Franklin Hotel 15',
 4751: '255 Gold',
 4778: '42 Henry Sling Henry E7',
 5094: '17th st',
 5153: 'Carlton n Flushing av Alderman 10th ward',
 5156: '176 Myrtle av',
 5329: 'City Hall Shades 317 Fulton',
 5477: '12 Fulton R Bass',
 5633: '91 Pearl',
 5667: 's hipmaster 199 Bridge Alderman 2nd Ward',
 6081: '286 Hicks',
 6174: '220 F',
 6558: '1 Mechanics',
 7066: '85',
 7136: '17 State',
 7319: '231 Jay',
 7361: '75',
 7963: '91',
 7965: '8 Tompkins',
 7995: '109 Navy',
 8172: '32 Hudson av Alderman 10th ward',
 8842: 'morocco f actory 17',
 9005: '153 Prospect',
 9223: '91 Pear',
 9318: '266 Hudson av',
 9321: '111 Atlantic',
 9574: '117',
 9838: '105',
 9893: 'Amity assessor 9th ward',
 10036: '51 Prince refused',
 11019: '9 Little n John Brooklyn',
 11047: '202 Fulton',
 11144: '151153',
 11199: '159 Myrtle av',
 11577: '144 Carll n Myrtle ay refused',
 11648: '194 Fulton',
 11701: '105',
 11731: '386 Hudson av',
 11918: 'Graham c Myrtle av Alderman 9th ward',
 12063: '86 Clinton Bichards Mrs',
 12579: '172',
 12943: '7 Cottage row',
 13339: '150 Court',
 13732: '137',
 13935: '14',
 14075: '107 Atlantic',
 14470: 'John c Bridge office 81 Front N Y',
 14501: '1S1 Tillary',
 14642: 'Classon n Flushing av Aiderman 11th ward',
 14658: 'Doctor Smith c Schermerhorn 1 assessor 11th ward',
 15062: '1 Jamcsc Front',
 15173: '42 Pacific n',
 15290: '85 Willoug',
 15613: 'Mansion House 121'}

In [72]:
df = df.rename({'Full Address': 'Full Address old'}, axis=1)

In [73]:
#part_after_h[4]

In [74]:
new_full_address = {}
for a in range(0, len(df)):
    try:
        new_full_address[a] = part_after_h[a]
    except:
        try:
            new_full_address[a] = part_before_and[a]
        except:
            new_full_address[a] = temp_replace_specials[a]

In [75]:
for a in range(0, len(df)):
    split_list_from_address = new_full_address[a].split()
    try:
        if split_list_from_address[-1] == '&':
            split_list_from_address = split_list_from_address[:-1:]
    except:
        pass
    try:
        if split_list_from_address[-1] == 'n':
            split_list_from_address = split_list_from_address[:-1:]
    except:
        pass
    try:
        if split_list_from_address[0] == '&':
            split_list_from_address = split_list_from_address[1::]
    except:
        pass
    new_full_address[a] = ' '.join(split_list_from_address)

In [76]:
def firstUpperCaseLetter(str) : 
    for i in range(0, len(str)) : 
        if (str[i].istitle()) : 
            return i
    return 0

In [77]:
for a in range(0, len(df)):
    test_string1 = new_full_address[a]
    if hasNumbers(test_string1)==False:
        loc_of_first_uppercase_letter = firstUpperCaseLetter(test_string1)
        new_full_address[a] = test_string1[loc_of_first_uppercase_letter:]

In [78]:
new_full_address[996]

'physician and surgeon Montague place 2d'

In [79]:
for a in range(0, len(df)):
    try:
        if new_full_address[a].index(' and ')>=0:
            print(a, new_full_address[a])
    except:
        pass

153 fortes music books and sta
242 66 and 58
310 Ailantic and Stat
334 Myrtle n Carlton av and Flushing
378 grocery and wood dealer junc of
386 Union coffee and spice mills Jay & Chapel
481 flower and green house trellises and ladies
496 Atlantic c Columbia and Columbia
508 89 Main and 69 Concord c Pearl
732 N Y Ship and Com
859 Water and Front
996 physician and surgeon Montague place 2d
1031 Hicks and Columbia
1175 Hoyt and Smith
1190 Atlantic and Pacific
1253 3d avb 15th and 16th st Go
1290 Columbiab State and Joralemon
1352 Washington and Adams
1361 Dock and Main office 1S1 Broadway NY h
1381 physician and surgeon Montague place 2d door from Court
1415 Fulton and Concord
1524 Myrtle n Carlton av and Flushing av n Kent av
1584 15 and 150 Atlantic tobacconist 36 Vesey N Y
1599 comb and curl store 218 Fulton op Tillary
1600 N Y Ship and Commercial List State n Powers
1647 State and Joralemon
1792 Court and Clinton
1814 Hicks and Hamilton av
1842 191 Clinton l and Fulton av
1887 Fulton and Furman
1888 35 and 41 Fultoti
1903 Water and Plymouth
1998 319 Goldb Willoughby and Fulton
2282 Burrell Emely & cupper and leecher 24 0 Fulton
2284 Flatbush turnpike and rail road
2513 manufr and dealer in hosiery 219 Fulton
2550 L I hotel and livery stable 27 Fulton
2591 Nostrand n Myrtle av and Classon n DeKalb av
2640 tin copper and sheet iron worker 135
2689 44 James room 6 and 11
2707 Bridge rd and 3d av Gowanus
2708 Court h Degraw and Sackett
2730 Union and Sackett
2817 Navy shades Navy c York and 20U York
3017 Willoughby and Fulton
3115 Smith and Court
3131 Henry and Clinton
3135 Bond and Hoyt
3148 Sth Ward 19th st and 3d av Gowanus
3200 Plymouth c Pearl and 47 Hudson av
3221 Willow and Hicks h 36 Amity
3374 Henry and Clinton
3411 Sackett and Union
3565 Hudson av and Debevoise
3713 3d av and 19th st GowanUS
3743 Adams and Pearl
3826 chemist and apothecary junction of Fuller and Clinton la 269 Bridge
3917 Clinton and Fulton av
3987 Flushing and Park av
4175 19th st and 3d av Gowanus
4314 26 Hudson av c John and Flushlng n Classon av
4414 Atlantic Bank and City Treasurer 55 Fulton
4430 Navy and Hudson av
4433 94 Sackett h Hicks and Columbia
4480 Hicks and Hamilton av
4494 feather beds mattresses paper hangings and carpet weaving 122 Fulton
4532 State and Joralemon
4673 Flatbush turnpike and Dean st
4707 129 Atlantic and Furman n Joralemon
4743 c 3d av and 16th st Gowanus
4912 Harrison and Degraw
4933 Henry and Clinton
4981 Columbia and State
5076 76 and 78 Fulton
5081 Lawrence h Myrtle av and Willoughby
5099 Hoyt h Atlantic and State
5155 Willoughby and Fulton av
5235 Middle and 3d av Gowanus
5391 Aretus Bailey and E Baldwin 15 Fulton c Water
5776 State and Hicks
5961 painter and marble paper manf 414 Atlantic
6026 Maine New Hampshire and Connecticut
6175 widow thread and needle store 98 Bridge
6207 upholst r and paper hanger 216 Fulton
6298 confectionary and ice cream saloon 269 Fulton op Pierrepont
6503 Sth ward hotel 3d av and ice cream saloon 3d av c 27th st Gowanus
6552 10th st and 3d av Gowanus
6564 21st st and 3d av Gow anus
6570 Brooklyn and N Y Express 99 Middagh
6881 179 Atlanticb Clinton and Court
6960 Penny Bridge rd and 3d av Gowanus
7058 Common Council and keeper City HallCity Hall
7105 9 and 11 Hicks
7111 Willoughby and Myrtle av
7357 75 and 77 Henry
7372 Raymond n Myrtle av Andrew B Hodges sheriff & and keeper
7458 Johnson h Pearl and Jay
7480 Jay and Bridge h 175 Bridge
7488 Washington and Adams h 126 Nassau
7507 Fulton av h Washington and Classon av
7591 Pearl h Water and Front
7620 Willoughby and Fulton h Pacific n Hoyt
7746 9th st and Gowanus lane
7906 State and Joralemon
7945 Flushing n Kent av Ridder John looking glass and picture frame maker Clove
7987 Hicks h Sackett and Degraw
8059 Clinton and Henry
8106 Amity h Clinton and Court
8151 Flushing and Myrtle av
8216 145 Myrtle av and proprietor of thc Bee Hive Hotel 147 Myrtle av
8219 Bond and Hoyt
8357 Bridge and Jay
8385 PUB LISIIERS OF BROOKLYN DAILY ADVERTISER BOOK AND JOB PRINTEHS 35 and 41
8479 Bond and Hoyt
8493 Court and Clinton
8558 fringe and tassel manufacturer and agent forSoria & Co French dycrs 189 Fulton
8559 Columbia n Fulton and 101 Atlantic and 154 Fulton
8585 attorney and counsellor and commissioner of deeds 45 Prince
8647 Bedford av and Skillman 6t
8729 Joralemon and Livingston
8797 President and Carll
8834 Plymouth and Water
8861 Notary Public Land and Loan agent office 307 Fulton li 19 Johnson
8887 22nd st h 3rd and 4th av Gowanus
8917 121 and 123 Hicks E R Yale proprietor Degraw
8932 Main c Front and Main c Water
8954 Atlantic and State
9008 26th st and 3d av Gowanus
9173 Blakes buildings Court h Baltic and Buller
9241 Myrtle and Park av3
9296 Joralemon and Livingston
9308 Bridge rd and 3d av Gowanus
9342 Water and Plymouth
9362 Henry and Montague pl
9365 gold pen and pencil maker 15 Beekman N Y
9370 Jay and Adams
9433 140 and 142 Fulton
9500 Blake s buildings Court h Baltic and Butler
9619 Johnson and Myrtle av BROOKLYN DIRECTOET
9669 Myrtle and DeKalb av
9690 Park and Flushing av
9705 Atlantic and State
9714 Gold and Bridge
9778 Atlantic and State
9839 Navy and Raymond
9925 stove and furnishing st ore 250 Fulton
9976 Smith and Hoyt
9997 Sackett and Degraw
10014 Water and Plymouth
10080 Fulton and Doughty
10153 111 State n Court Al Coy JamesBergen h Powers and 4th av
10181 Plymouth and Water
10191 tin and copper smith 194 Bridge
10195 Jay and Bridge
10196 State and Atlantic
10229 Columbia st and Hamilton av
10277 Luquier and Mill
10337 Tillary and Myrtle av
10429 tin and copper smith 114 Hudson av
10527 Bridge and Jay
10553 Luquier and Mill
10566 Jay and Bridge ABLaughlin PJohn n Jay
10604 Myrtle av and Willoughby
10631 Columbia st and Hamilton av
10635 74 Main c York and variety store 61 Main
10714 JVashington and Liberty h 32 Stanton
10779 President and Carroll
10783 President and Carroll
10878 Harrison and Degraw
11003 Agency and General Employment office 223 Fulton et
11110 Myrtle and Park av
11124 Atlantic and State
11174 Columbia and Henry
11225 42 Fulton and 8 Prospect
11396 Flatbush turnpike n Powers and Myrtle n Carlton av
11410 Fisherman s Hall Gowanus bridge and Hamilton av n the Penny bridge
11454 Teacher oi Vocal and Instrumental
11473 Flushing n Franklin av and Myrtle c Classon av
11540 Gold and Hudson av
11747 90 and 92 Pacific street between Smith and Hoyt residence
11800 Butler n Bond and 116 Hud son av
12126 York and Prospect Piiley Hugh 47 Little n Water
12225 Clinton and Henry h 57 Tillary
12231 Wolcott and Richard sts Red Hook
12260 74 Sands LLJAM counsellor and attorney & Alderman
12326 316 State h Bond and Nevins
12327 316 State h Bond and Nevins
12361 Jay and Bridge
12439 55 Adelphi h Myrtle and Park av
12514 Smith and Hoyt
12515 Smith and Hoyt
12658 Bridge and Gold h Duffield h Willoughby st and Myrtle av
12675 Front and Water
12736 Brooklyn and N l Express 84 Schermerhorn
12739 91 Adams c Prospect and Nassau c Bridge ton n Degraw
12744 Myrtle and Willoughby st
12780 Adams and Pear & st
12793 Front and H ater
12798 Sth av h 13th and 14th sts
13023 tin and sheet iron worker 5 Lawrence
13157 Nevins and Bond
13247 Carlton h Myrtle and DeKalb av
13266 copyist county clerks office and commissioner of deeds 419 Hudson av
13347 104 York and 120 York
13378 Atlantic Union h Columbia and Canton Livingston
13402 Sackett h Court and Clinton
13451 Spooner & Paddock attorneys and counsellors office 3 Front
13531 Court and Smith
13546 Johnson and Myrtle av305 Pearl N Y
13630 Court and Baltic
13656 Myrtle and Flushing av
13688 Union h Columbia and Clinton
13739 Bridge and Gold h 105 Johnson
13791 Park and Myrtle av
13842 3 and 5 Furman
14063 81 and 83 Fulton
14086 milliner and hat presser 25G Fulton
14512 271 Pearl Y oorhees Jeremiah counsellor at law and commissioner of
14518 Nevins and Powers
14539 Skillman st and Bedford av
14542 4th av and 10th st Gowauus
14744 Harrison and Degraw
14748 ind builder 80 Livingston and Smith c Dean
14774 Gold and Hudson av
14859 Tompkins place n Harrison Warrington Mrs John widow thread and needle store 32 Hicks
14903 Willoughby st and Fulton av
14936 Pacific and Amity h 19 Myrtle av
15085 Schermerhorn h Smith and Hoyt
15106 Sackett n Court and Degraw c Strong pl
15123 Henry and Clinton h 214 Atlantic
15139 White & Kirksash and blind makers Livingston c Bond
15279 tin and sheet iron worker 16S Jay
15364 155 and 157 Adams
15435 Jay and Bridge
15462 tin plate and sheet iron worker 184 Nassau
15469 Flushing and Park av
15486 Atlantic and Flatbush turnpike

In [80]:
new_full_address

{0: '168 Hudson av',
 1: 'Dean n Vanderbilt av',
 2: '82 Poplar',
 3: 'education of',
 4: 'Union n Court',
 5: 'Pacific n Boerum',
 6: '25 Front',
 7: 'Joyalemonn',
 8: 'Kent ay north',
 9: 'Bond c State & Hoyt',
 10: '262 Atlantic',
 11: '74 Concord',
 12: '115 Johnson',
 13: '261 Marshall',
 14: '301 Gold',
 15: '23 Prince',
 16: '288 Hudson av',
 17: 'shoemaker Navy & Sands 4',
 18: '116 Concord',
 19: '180 Henry',
 20: '5 York i',
 21: '3 Kelsey s alley',
 22: 'education of boys 75 Columbia',
 23: 'Johnson & Fulton',
 24: '43 Cranberry',
 25: '59 Hoyt',
 26: '72 Columbia',
 27: '34',
 28: '266 day',
 29: '45 High',
 30: '124 Nassau',
 31: '22 Degraw n Smith',
 32: '3d avy c 24th st Gowanus',
 33: '152 Hudson av',
 34: 'Dean n Smith',
 35: 'Flushing av n Navy Yard',
 36: 'Myrtle c Nostrand av',
 37: '101 State',
 38: 'widow 99 State',
 39: '176 York',
 40: '8 Tillary',
 41: 'laborer 22d st n 3d av Gowanus',
 42: 'Pacific n Oxford',
 43: 'Hudson av n Lafayette',
 44: '210 Atlantic',
 45: 'Butler n Smith',
 46: '321 Henry',
 47: '34 Wyckoff',
 48: 'Hoyt n State',
 49: '163 Pearl',
 50: '346 Fulton op Adams',
 51: '41 Gold',
 52: '108 High',
 53: '6 Montague place',
 54: 'Jay c Front',
 55: '109 High',
 56: 'Sands n Navy',
 57: '107 Concord',
 58: '40 Prince',
 59: '94 Sands',
 60: 'Front n day',
 61: 'Front & Jay',
 62: 'grocer 2istst n 4th av Gowanus',
 63: 'Clinton',
 64: '35',
 65: 'Hamilton st Red Hook',
 66: '296 Atlantic',
 67: 'Warren',
 68: '113 Livingston',
 69: '100 Orange',
 70: '98 Duffield',
 71: 'agent for the hire of real estate 69 Cranberry',
 72: '21 Carlton ay',
 73: 'Flushing av',
 74: 'Classon n Myrtle av',
 75: 'Myrtle n Classon av',
 76: '118 Gold',
 77: '73 Prospect',
 78: '265 Hudson ay',
 79: '33 Cranberry',
 80: 'Bridge & Sands',
 81: 'Livingston n Hoyt',
 82: '258',
 83: '180 York',
 84: '217 Adams',
 85: '43 Adelphi',
 86: '57 York',
 87: 'Hudson & DeKalb ay',
 88: 'Dean n Powers',
 89: 'Franklin av',
 90: 'Flushing av & Graham',
 91: '227 Atlantic',
 92: 'Kent n Flushing av',
 93: '116 Johnson',
 94: '98 Ilenry',
 95: '36 Tillary',
 96: '307 Bridge',
 97: 'Clinton av',
 98: 'Powers',
 99: 'Atlantic',
 100: '197 Wash',
 101: '121 Hicks',
 102: '73 Livingston',
 103: '56 Stanton',
 104: '72 Sands',
 105: 'Gold c Fulton ay',
 106: '102 Naseau',
 107: '153 Prospect',
 108: '65 Poplar',
 109: '103 Willoughby',
 110: '305 Gold',
 111: 'Park n Vanderbilt av',
 112: 'Kent n Flushing av',
 113: 'Johnson & Adams',
 114: '33 Cottage row Furman',
 115: '52 State',
 116: 'Willow place & State',
 117: 'Clinton n Myrtle av',
 118: '56 Baltic',
 119: '108 Atlantic',
 120: '103 Hadson av',
 121: 'Flushing av n Navy',
 122: '16 Myrtle av',
 123: '209 Henry',
 124: 'Hicks n Luqueer',
 125: '125 High',
 126: '35 Douglass',
 127: '219 Front',
 128: '3d av c 27th st',
 129: '96 Front c Main',
 130: '53 Fulton',
 131: 'Atlantic & Bond',
 132: 'Plymouth n Pearl',
 133: '57 Johnson',
 134: '217 Pearl',
 135: 'Gold & Prospect',
 136: '61 Court',
 137: 'Hicks b',
 138: '36 Navy n Park ay',
 139: '63 Atlantic',
 140: '56 Atlantic',
 141: '6 Kelsey',
 142: '7 Middagh',
 143: '279 Gold',
 144: 'Kent av north',
 145: '8 3 Middagh',
 146: '19',
 147: '1 McKenney',
 148: '295 Prospect',
 149: '43',
 150: '10 Vine',
 151: '393 Atlantic',
 152: '50 Middagh',
 153: 'fortes music books and sta',
 154: '3 York',
 155: 'Flushing n Kent av',
 156: 'Tillary c Canton',
 157: 'Crowhill',
 158: '77 York',
 159: '167 York',
 160: '1 Tillary',
 161: '16 Cottage Row Furman',
 162: 'Clermont',
 163: '15 Prospect',
 164: '95 Prospect',
 165: 'Sackett n Clinton',
 166: '110 Hudson av',
 167: '114 Hudson av',
 168: '68 York',
 169: '49 Middagh',
 170: 'Fronte Washington',
 171: '43 Main',
 172: '108 Gold',
 173: '39 Carlton av',
 174: '18 st n 4th av Gowanus',
 175: '80 High',
 176: '128',
 177: '4th ward hotel Fulton c Myrtle av',
 178: '4 Franklin Place',
 179: 'Bedford n Myrtle ay',
 180: 'Flushing c Franklin ay',
 181: 'Flushing av n Spencer',
 182: 'Spencer n Flushiug ay',
 183: 's31 53 Hudson ay',
 184: '61 Hoyt',
 185: '152 Myrtle',
 186: 'Myrtle Av n Steuben',
 187: '37',
 188: 'Wyckoff n Bond',
 189: '188 Water n Hudson ay',
 190: '108 Clinton c State',
 191: '155 Nassau',
 192: '20 Douglass',
 193: 'Cheeyer pln Harri',
 194: '195 Atlantic',
 195: '149 Prospect',
 196: '102 Fulton',
 197: 'Mercein o James',
 198: 'Carlton',
 199: '144 Jay',
 200: '3d ay',
 201: 'Concard & Gold',
 202: 'farmer 3d ayn 27th st Gowanus',
 203: 'Hudson n Fulton av',
 204: '47 Green Lane',
 205: '182 Adams',
 206: '838 Henry',
 207: '16 st n 3d ay Gowanus',
 208: 'Slate n Bond',
 209: 'Smith c Douglass',
 210: 'Pacific op Washington av',
 211: 'Gowanus 1d',
 212: '42 Main',
 213: 'Raymond n Myrtle av',
 214: '126 Prospect',
 215: 'De Kalb av',
 216: '312 Atlantic',
 217: '13 Cottage row Columbia n Degraw',
 218: 'Front c Garrison',
 219: '100 Gold',
 220: '61 Atlantic',
 221: '3d av Gowanus',
 222: 'Hamilton ayn Atlantic Dock',
 223: '95 Fulton',
 224: '166 Prospect',
 225: 'Clove rd Bedford',
 226: 'Red Hook point',
 227: '147 Hicks',
 228: '160 Atlantic',
 229: '142 Carll',
 230: 'Classon n Myrtle ay',
 231: 'milkman 5th av n Atlantic',
 232: '130 Myrtle av',
 233: 'Jamaica rd n Atlantic st',
 234: '18 Lawrence',
 235: '195 Washington',
 236: '95 Fulton',
 237: 'Smith ce Wykoff',
 238: '141 Atlantich 108 Pineapple',
 239: 'Court n Pacific',
 240: 'Montague place h Henry',
 241: '37 Front',
 242: '66 and 58',
 243: 'Water n Dock',
 244: '75 Water',
 245: '90 Smith',
 246: 'Columbia & Summit',
 247: '85 Prospect',
 248: '99 Navy',
 249: 'Fulton shades 311 Fulton',
 250: 'Hamilton av',
 251: '91 Concord',
 252: '84 Hudson av',
 253: 'Harrison 2',
 254: 'Place c Court',
 255: 'Henry',
 256: '3rd av Gowanus',
 257: '150 Joralemon',
 258: '3d av Gowanus',
 259: '16 Poplar',
 260: '84 Tillary',
 261: '37 Chauncy Court Wall N',
 262: '82 Cottage row Columbia n Union',
 263: '120 Prince',
 264: '3d av Gowanus',
 265: '2d av Gowanus',
 266: '8 3d av Gowanus',
 267: 'VY & alderman 8th Ward 3d avy Gowanus',
 268: '3d av Gowanus',
 269: '39',
 270: '63 Willoughby',
 271: '3dav Gowanus',
 272: '15 Poplar',
 273: '25 Hicks',
 274: 'embossed paper 3d Av n 18th Gowanus',
 275: '3d av Gowanus',
 276: 'Prespect Hill',
 277: '160 William N Y 56 Adams',
 278: '161 Bridge',
 279: 'Washington av c Fulton av',
 280: 'Frank',
 281: 'Myrtle av',
 282: 'Lawrence n Fulton ay',
 283: 'Columbia n Amity',
 284: 'Dean n Powers',
 285: 'Tillary & Prince',
 286: '68 Bridge',
 287: 'Gowanus Jane c 15th st',
 288: '51 Main',
 289: 'Tillary c Prince',
 290: 'Carlton e Myrtle av',
 291: 'Myrtle av & Jay & High',
 292: '137',
 293: '135 High',
 294: '83 Henry',
 295: '5th av n 12th st Gowanus',
 296: '136 High',
 297: 'Myrtle av',
 298: 'Warren c Nevin',
 299: 'Park c Vanderbilt ay',
 300: 'Sparkman & Kelsey s oil cloth',
 301: 'Washington av',
 302: 'Myrtle av & Sanford',
 303: 'Lawrence n Fulton ay',
 304: '1 Atlantic',
 305: '123 Atlantic',
 306: '85 Livingston',
 307: '156 Bridge',
 308: '121 Willoughby',
 309: '43 Pierrepont',
 310: 'Ailantic and Stat',
 311: '58 Doughty',
 312: '331 Gold',
 313: '29 Cottage row Furman',
 314: '113 Navy',
 315: '125 Hudson av',
 316: '89 Pineapple',
 317: '51 Main',
 318: '34 Hicks',
 319: '89 Main n Water',
 320: '17 Atlantic',
 321: '286 Hicks n Pacific',
 322: '67 Nassau',
 323: '81 High',
 324: 'Bedford',
 325: '107 Bridge',
 326: '102 York',
 327: 'Hed Hook',
 328: 'Atlantic',
 329: '14 Strong Place n Harrison',
 330: '76 Washington',
 331: '148 York',
 332: '72 Washington',
 333: '105 Front',
 334: 'Myrtle n Carlton av and Flushing',
 335: 'House 12 Fulton',
 336: '27 York',
 337: '27 York',
 338: '61 Fulton',
 339: 'Flatbush road n Prospect Hill',
 340: 'Myrtle ave Spencer & Place',
 341: '14 Sydney',
 342: '41 Adelphi',
 343: '26 Lafayette',
 344: '39 Myrtle ay',
 345: 'Flatbush turnpike n Powers',
 346: '71 Poplar',
 347: '33 Hicks',
 348: '80 Fulton',
 349: '52 Myrtle ay c J ay',
 350: 'Plymouth n Jay',
 351: '134 Henry',
 352: '229 Hicks',
 353: 'Willoughby c Gold',
 354: '41',
 355: 'State',
 356: '65 Hicks',
 357: '91 Henry',
 358: '96 Hicks',
 359: '96 Hicks',
 360: '58 Hicks',
 361: '119 Columbia n Clark',
 362: '71 Hicks',
 363: '114 Navy',
 364: '207 Henry',
 365: '27th st n 3d av Gowanus',
 366: 'Bedford n Park av',
 367: 'Douglas c Smith',
 368: '22d st 1 3d ay Gowanus',
 369: '5 Mill n Court',
 370: 'Jamaica read op Portland st',
 371: 'Smith n Sackett',
 372: '65 Nassau',
 373: '90 Prince',
 374: '170 York',
 375: 'Canton c Tillary',
 376: '79 Popiar',
 377: '175 Gold',
 378: 'grocery and wood dealer junc of',
 379: 'State n Powers',
 380: '2 York n James',
 381: '64 Lawrence',
 382: '119 Willow',
 383: '79 Poplar',
 384: '119 Willow',
 385: '145 Nassau',
 386: 'Union coffee and spice mills Jay & Chapel',
 387: '150 Joralemon',
 388: '110',
 389: 'machine shop',
 390: 'Smith n Schermerhorn',
 391: 'Boerum',
 392: '43 Johnson',
 393: '118 Adams',
 394: 'Columbia & Warren',
 395: 'Bergen & Smith',
 396: '6 Tiffany place',
 397: 'Carll n Myrtle av',
 398: 'Navy n DeKalb ay',
 399: '76 Lawrence',
 400: '61 Wall st NY',
 401: 'Myrtle av',
 402: '3d av n 18th st Gowanus',
 403: '65 Lawrence',
 404: '40 Carlton av',
 405: '121 Adams',
 406: 'Pacific n Underhill ay',
 407: 'Fulton av c Hoyt',
 408: '78 York',
 409: '4 Linden row Fulton',
 410: '187 Concord',
 411: 'Classon av & Hickory',
 412: '8 89 Pineapple',
 413: 'Navy n Nassau',
 414: 'Trinity Chureh 250 Adams',
 415: '101 Pearl',
 416: '175 Adams',
 417: '25 Fulton',
 418: 'Hoytn Dean',
 419: '5 Prince',
 420: 'Water n Jay',
 421: 'Sands & Pearl',
 422: 'Columbia n Amity',
 423: 'Court n Pacific',
 424: '136 High',
 425: '214 Front',
 426: '134 Adams',
 427: 'sn 54 Hudson av',
 428: 'Dufeld c Fulton av',
 429: 'Bridee rd Gowanus',
 430: '110 Jay',
 431: 'Navy a Myrtle av',
 432: 'widow of R OC 70 Sands',
 433: 'Hudson ave Concord',
 434: '44 Hudson ay',
 435: '90 Main',
 436: '5 Cottage place Columbia',
 437: '52 Prince',
 438: '95 Concord',
 439: 'York',
 440: 'State c Smith',
 441: '14 James',
 442: '159 Gold',
 443: '74 Jay',
 444: 'widow 97 Prospect',
 445: '109 Gold',
 446: 'Myrtle av',
 447: 'Henry 267 Hudson av',
 448: '145 York',
 449: '90 Washington',
 450: 'Butler n Court',
 451: '163 Frout',
 452: '90 Fulton N',
 453: 'York op Navy',
 454: '234 Hudson av',
 455: '143 Duffield',
 456: '143 Duffield',
 457: '132 Sands',
 458: 'Powers n Fulton',
 459: '348 Marshall',
 460: 'blacksmith 246 Marshall',
 461: 'Hudson ay & Marshall',
 462: '177 Gold',
 463: '199 Pearl',
 464: '124 Smith',
 465: 'Parl n Clinton av',
 466: 'u s w 32 Hudson av',
 467: '36 State',
 468: 'Degraw op Strong Place',
 469: 'Schermerhorn',
 470: 'Hamilton av n Ferry & Boerum',
 471: 'Hoyt u State & Classon av',
 472: '171 Fulton bh Myrtle',
 473: 'Pacific n Hoyt',
 474: '6 Joralemon',
 475: 'Little c United States',
 476: '316 Gold',
 477: 'Myrtle av n Classon ay',
 478: 'Plymouth n Jay',
 479: '43',
 480: '75 Pineapple',
 481: 'flower and green house trellises and ladies',
 482: '30 Atlantic n Columbia',
 483: '119 Court',
 484: 'Bridge',
 485: 'Chemist 88 Myrtle ay c',
 486: 'apothecary 115',
 487: 'Columbia n State & Atlantic',
 488: '181 Fulton',
 489: 'Oxford st n Jamaica rd',
 490: '261 Marshall',
 491: '104 Concord',
 492: '65 Fulton',
 493: '70 Washington',
 494: '71 Main',
 495: '96 Clinton',
 496: 'Atlantic c Columbia and Columbia',
 497: '6 Glake',
 498: '178 Washington',
 499: '22 Lawrence',
 500: '58 Lawrence',
 501: '82 Adams',
 502: '48 Concord',
 503: '102 Middagh',
 504: 'Montague place',
 505: '257 Gold',
 506: '123 Dufheld',
 507: 'Liberty c Sprague Place',
 508: '89 Main and 69 Concord c Pearl',
 509: 'widow 15 High',
 510: 'Boerum n Pacific',
 511: '137 Hicks',
 512: '225 Bridge',
 513: '77 Concord',
 514: '22 High',
 515: '35 chapel',
 516: 'Clove Road Bedford',
 517: 'Franklin n Myrtle av',
 518: '134 Carll',
 519: 'Penny Bridge rdn 3d av Gowanus',
 520: '3d ay n 16th st Gowanua',
 521: '3d av c Bridge ra wo',
 522: '61 State',
 523: '40 Myrtle av',
 524: '77 Willow',
 525: '163 Prospect',
 526: '10 Harper Court Jay st',
 527: '11 Talman',
 528: '139 Nassau',
 529: 'Myrtle av',
 530: '26 Livingston',
 531: '55 Atlantic',
 532: '295 Pearl',
 533: '132 Nassau',
 534: 'Plymouth n Jay',
 535: '19 Union',
 536: '143 Couwtn',
 537: 'Spencer n Myrtle av',
 538: 'Clove road Bedford Fulton av',
 539: 'Washington ava',
 540: 'gunner vu s N 127 Mudson av',
 541: '139 Sands',
 542: '267 Jay',
 543: '90 Harrison',
 544: 'Myrtle o',
 545: '90 Columbia',
 546: '40 Tillary',
 547: '131 Atlantic',
 548: '69 Fulton bh 112 Fulton',
 549: '181 Atlantic',
 550: '49 Willoughby',
 551: 'Joralemon & Livingston',
 552: 's n 147 York',
 553: 'Vanderbilt n Park av',
 554: '172 York',
 555: 'Park n Franklin av',
 556: 'Spencer n Myrtle av',
 557: 'Walworth n Park av',
 558: 'Pearl n Water',
 559: 'Fleet op Boliver',
 560: '45',
 561: 'Atlantic n Powers',
 562: '61 Bridge',
 563: '208 Gold',
 564: '240 Henr',
 565: '144 Hicks',
 566: 'Clinton n Amity',
 567: '222 Jay',
 568: 'Cottage row Furman',
 569: '27 Monroe pl',
 570: '7',
 571: '71 Remsen',
 572: '223 Adama',
 573: 'Powers n Schermerhorn',
 574: '325 Henry',
 575: '5th av House 27thet n Sth av',
 576: 'Clinton av n Jamaica rd',
 577: '4 Boardman Place Court st',
 578: 'Kent av North',
 579: 'Pacific n Court',
 580: '59 Atlantic',
 581: '52 Sands',
 582: 'Boerum n Dean',
 583: '110 Willoughby',
 584: '341 Atlantic',
 585: 'Smith & Douglasa',
 586: '345',
 587: 'Bridge rd Gowanus',
 588: '18 Cottage row Columbia n Joralemon',
 589: 'clerk 61 Baltic',
 590: 'Kent av north',
 591: 'Kent av north',
 592: '123 York',
 593: 'Nostrand n Myrtle av',
 594: 'Navy yard',
 595: 'Kent ay north',
 596: '303 Fulton',
 597: 'Bedford Av n Willoughby',
 598: 'York',
 599: '290 Gold',
 600: '99 High',
 601: '143 Tillary',
 602: 'Bedford',
 603: '118 Fulton',
 604: '142 Johnson',
 605: 'Hoyt u Dean',
 606: '111 Wiiloughby',
 607: '18 Hicks',
 608: '270 Fulton',
 609: '18 Hicks',
 610: 'Classon & Flushing av',
 611: 'Classon n Flushing ay',
 612: 'Hicks c Degraw',
 613: '270 Fulton',
 614: 'Harrison',
 615: 'Park & Franklin ay',
 616: 'Stale & Willow place',
 617: 'Myrtle c Nostrand av',
 618: 'ke',
 619: '15 Atlantic',
 620: '154 Johnson',
 621: '270 Hicks n State',
 622: 'Prospect c Washington',
 623: 'Myrtle av',
 624: '59 Pacific',
 625: 'Spencer n Park av',
 626: '96 Harrison',
 627: '259 State',
 628: 'Flushing ay n Bedford av',
 629: 'Red Hook',
 630: '152 Prospect',
 631: '27 Talman',
 632: 'Gowanus n Bridge road',
 633: '103 Willow',
 634: '259 Jehn',
 635: '84 Myrtle ay',
 636: '357 Hudson ay',
 637: 'Myrtle ay',
 638: '249 Bridge',
 639: '7 7 Degraw',
 640: 'Pacific e Henry',
 641: 'Flatbush turnpike n Atlantic',
 642: '10 Furman n Doughty',
 643: 'Water n Jay',
 644: '43 Atlantie',
 645: 'brick yard 3dave',
 646: '3d ay Gowanus',
 647: '93 Cranberry',
 648: '44 Sydney place',
 649: 'Front & Garrison',
 650: '106 Bridge',
 651: '148 High',
 652: 'Hudson av',
 653: '29 Talman',
 654: '179 Clinton',
 655: '10 Monroe place',
 656: '67 Baltic',
 657: '182 Jay',
 658: '3d av c Bridge road Gowanus',
 659: '67 Baltic',
 660: '157 Cedar N Y bh 67 Baltic',
 661: '359 Hudson av',
 662: '182 Jay',
 663: '122 Adams e High',
 664: 'N & bh 8 Willow place',
 665: '264 Hicks',
 666: '270 Washington',
 667: '108 Navy',
 668: '62 Front',
 669: 'Willow',
 670: 'Columbia & Warren',
 671: 'Park n Vanderbilt av',
 672: '255 Joha',
 673: 'Flushing ay',
 674: 'Classon',
 675: 'Columbia & Warren',
 676: '3d av c 16th st Gowanus',
 677: 'Classon n Flushing av',
 678: '61 Tillary',
 679: '36 Sackett',
 680: '270 Washington',
 681: '45 Willow',
 682: 'Dufiield n Fulton av',
 683: 'Flatbush turnpike c Atlantic',
 684: '182 Atlantic',
 685: 'Water n Bridge',
 686: '16 Prince',
 687: '289 Gold',
 688: '22 State',
 689: '60 Raymond',
 690: 'Water c Pearl',
 691: 'Falton op Jchnson & Pearl',
 692: '285',
 693: '54 Prospect',
 694: 'President n Hamilton av',
 695: 'Vanderbilt ay n Dean',
 696: '9 Front',
 697: 'N & bh 8d av c 16th sti',
 698: '808 Atlantic',
 699: 'Willoughby',
 700: '15 Talman',
 701: 'Hoyt & Douglass',
 702: '40 York',
 703: 'Franklin ay n De Kalb av',
 704: '2',
 705: 'Navy n Lafayette & Lawrence',
 706: '62 Nassau',
 707: '152 Sands',
 708: '3 Tillary',
 709: '179 Myrtle av',
 710: '62 Tillary',
 711: 'Houston n Myrtle',
 712: '107 Atlantic',
 713: 'Hudson & De Kalb ay',
 714: 'Summit',
 715: '66 Hudson av',
 716: 'Boerum 2',
 717: '8 Boardman Place Court st',
 718: '29 State',
 719: '45 James',
 720: '20 Hicks',
 721: '16 Stanton',
 722: '123 Court',
 723: '303 Fulton',
 724: '2 Barbarine',
 725: '103 Tillary',
 726: 'Franklin ayn Flushing av',
 727: 'Hamilton',
 728: '1 Hloward',
 729: 'store 218',
 730: '30 Clinton',
 731: 'St Thomas Church 287',
 732: 'N Y Ship and Com',
 733: 'State n Powers',
 734: '37 Main c Water',
 735: '105 Willoughby',
 736: '45 Myrtle av',
 737: 'Kent av n Flushing av',
 738: 'Flushing avy ec Cumberland',
 739: 'Spencer n Flushing av',
 740: '288 Hudson av',
 741: 'Water n Hudson ay',
 742: '118 Hicks',
 743: 'Kent av c Park av',
 744: 'Myrtle c Franklin av',
 745: '83 Henry',
 746: 'Fleetn Willoughby',
 747: '101 Gold',
 748: '99 Nassan',
 749: 'Dean n Hoyt',
 750: 'Cumberland n Park ay',
 751: '153 Navy',
 752: '83 Cranberry',
 753: '4 Blake',
 754: 'Columbia & Union place',
 755: 'carpenter 21st n 4th ay Gowanus',
 756: '80 Nassau',
 757: 'farmer 21st n 4th av Gowanus',
 758: 'mason 2ist stn 4th av Gowanus',
 759: 'truckman 21st n 4th av Gowanus',
 760: '188 Fulton',
 761: 'widow 17 Schermerhorn',
 762: '143 Washington',
 763: 'proprietor Catherine ferry 143 Washington',
 764: 'Boerum n Dean',
 765: 'Stanton c Nassau',
 766: '156 Johnson',
 767: '84 Middagh',
 768: '110 Prospect',
 769: '21',
 770: 'Cottage place 106 Columbia',
 771: 'Wyckoff n Bond',
 772: 'Bergen n Powers',
 773: 'Raymond',
 774: 'Livingston n Hoyt',
 775: 'Bergen',
 776: '207 Front',
 777: '57 Wyckoff',
 778: 'Fulton av c Gold',
 779: 'Prospect Hill',
 780: 'Carlton & Park ay',
 781: '28 Everitt',
 782: 'Red Hook',
 783: 'Red Hook',
 784: '380 Hudson av',
 785: '135 Nassau',
 786: 'Court n Pacific',
 787: 'Court n Pacific',
 788: '18 Talman',
 789: 'widow 2 Debevoise',
 790: '40 Carlton av',
 791: '8 Vine',
 792: 'Alley n Fulton & NY',
 793: '43 Water office 181 Broadway',
 794: '26 Fulton John Jones Proprietor',
 795: 'Division n DeKalb av',
 796: '34 Joralemon',
 797: '21 Sackett',
 798: '80 York',
 799: 'Court c Dean',
 800: '3 Jay n Plymouth',
 801: '64 Pacific',
 802: '155 Jay',
 803: 'Col',
 804: 'Hamilton av',
 805: '234 Hudson av',
 806: '15 College Place',
 807: 'Bond n State',
 808: 'Adams',
 809: '5 Monroe Place',
 810: 'Prince & road & 9th st',
 811: 'Gowanus',
 812: '98 Boerum',
 813: '155 Sands c Gold',
 814: 'Willow c Pacific',
 815: '155 Jay',
 816: '180 Nassau',
 817: '9 Prospect',
 818: '179 Concord',
 819: 'Borenm c',
 820: 'stone U Sdry dock 271 Peark',
 821: '82 Livingston',
 822: 'Boerum n Living',
 823: 'Water b',
 824: '64 Jay',
 825: '64 Jay',
 826: '105 Washington',
 827: 'Kent n DeKalb ay',
 828: 'Kent n Flushing a',
 829: 'Classon',
 830: '33 Myrtle ay',
 831: 'Columbia n Sackeit',
 832: '44 Baltic',
 833: '140 Furmanh 37 Willow',
 834: '4 Vine',
 835: '191 Clinton',
 836: '2nd Ward 39 Front',
 837: '231 Pearl',
 838: 'Amity n Court',
 839: '7 Water',
 840: '72 Adams',
 841: 'Hicks & Poplar',
 842: '97 Concord',
 843: '24 Garden',
 844: 'Red Hook',
 845: '43 Wyckoff n Smith',
 846: '146 High',
 847: 'baker Cranberry & Henry & 95 Myrtle av',
 848: 'Gold bh',
 849: 'Prince & Myrtle',
 850: '149 Myrtle av',
 851: 'Myrtle Av n Raymond',
 852: '23',
 853: 'Myrtle ay n Raymond',
 854: '143 Fulton',
 855: '4th av',
 856: '54 Fulton',
 857: 'Tillary n Navy',
 858: '60 Carlton n Myrtle av',
 859: 'Water and Front',
 860: '38 Concord',

In [81]:
#temp_replace_specials[497]

In [82]:
df['Full Address'] = new_full_address.values()

In [83]:
for a in range(0, len(df)):
    try:
        if len(part_after_and[a])>0:
            pass
    except:
        part_after_and[a] = ''

In [84]:
for a in range(0, len(df)):
    try:
        if len(part_before_h[a])>0:
            pass
    except:
        part_before_h[a] = ''

In [85]:
part_after_and_complete = collections.OrderedDict(sorted(part_after_and.items()))
part_before_h_complete = collections.OrderedDict(sorted(part_before_h.items()))

In [86]:
df['part after and'] = list(part_after_and_complete.values())
df['part before h'] = list(part_before_h_complete.values())

In [87]:
#df.to_csv('/Users/prajwal/Desktop/Columbia/C4SR/tesseract lib/mn 1850/data/MN_1850 tesseract spl removed.csv')
df.to_csv('/Users/prajwal/Desktop/Columbia/C4SR/tesseract lib/bk 1850/data/bk_1850_spl_removed.csv')