In [1]:
import pandas as pd
import numpy as np

In [2]:
#df = pd.read_excel('/Users/prajwal/Desktop/Columbia/C4SR/mn_1880/not so confident.xlsx')

In [3]:
#df = pd.read_csv('/Users/prajwal/Desktop/Columbia/C4SR/tesseract output/MN_1880_final_output_tesseract.csv')
df = pd.read_csv('/Users/prajwal/Desktop/Columbia/C4SR/tesseract lib/mn 1850/data/MN_1850 tesseract spl removed.csv')

In [4]:
#df_slice1 = df.loc[df['filter1']==1]

In [5]:
df_slice1 = df

In [6]:
try:
    df_slice1 = df_slice1.rename({'clean address': 'clean_address'}, axis=1)
except:
    pass
try:
    df = df.rename({'clean address': 'clean_address'}, axis=1)
except:
    pass

In [7]:
#slice1_addresses = list(dict(df_slice1['clean_address']).values()) #was initially uncommented



#slice1_addresses = list(dict(df_slice1['clean address']).values())

In [8]:
slice1_addresses = list(dict(df_slice1['Full Address']).values())

In [9]:
modified_clean_address = df['Full Address'].str.replace('Ã¢Â\x80Â\x99',"'").str.replace('Ã¢ÂÂ',"'").str.replace("Ã¢Â\x80Â\x98","").str.replace("Ã¢Â\x80Â\x9c","").str.replace("Ã¢Â\x80Â\x9d","")


"""


#modified_clean_address = df['clean_address'].str.replace('Ã¢Â\x80Â\x99',"'").str.replace('Ã¢ÂÂ',"'").str.replace("Ã¢Â\x80Â\x98","").str.replace("Ã¢Â\x80Â\x9c","").str.replace("Ã¢Â\x80Â\x9d","")
modified_clean_address = modified_clean_address.str.replace("hN", "h N")
print(modified_clean_address[0])
modified_clean_address = modified_clean_address.str.replace(".5 ", " ")
print(modified_clean_address[0])
modified_clean_address = modified_clean_address.str.replace(",h ", ", h ")
print(modified_clean_address[0])
modified_clean_address = modified_clean_address.str.replace(",h", ", h ")
print(modified_clean_address[0])
modified_clean_address = modified_clean_address.str.replace(", h.", ", h. ")
print(modified_clean_address[0])
modified_clean_address = modified_clean_address.str.replace(", h .", ", h. ")
print(modified_clean_address[0])
modified_clean_address = modified_clean_address.str.replace("H udson", "Hudson")
modified_clean_address = modified_clean_address.str.replace("'wav", "'way")
modified_clean_address = modified_clean_address.str.replace("B'way", "Broadway")
modified_clean_address = modified_clean_address.str.replace("B way", "Broadway")
modified_clean_address = modified_clean_address.str.replace("B'kly n", "B'klyn")
modified_clean_address = modified_clean_address.str.replace(",n", " n")
modified_clean_address = modified_clean_address.str.replace("W.h", " Wh")
modified_clean_address = modified_clean_address.str.replace("h-", " h ")
modified_clean_address = modified_clean_address.str.replace("h-", " h ")
modified_clean_address = modified_clean_address.str.replace("-h.", "h.")
#modified_clean_address = modified_clean_address.str.replace("H()", "h.")
#modified_clean_address = modified_clean_address.str.replace("*", " ")
#modified_clean_address = modified_clean_address.str.replace("h r.", "h r")

#modified_clean_address = modified_clean_address.str.replace(".h", ", h.")

#modified_clean_address = modified_clean_address.str.replace("^h", "  h")
#modified_clean_address = modified_clean_address.str.replace("h*", "  h ")

#modified_clean_address = modified_clean_address.str.replace(". .", " ")
"""

'\n\n\n#modified_clean_address = df[\'clean_address\'].str.replace(\'Ã¢Â\x80Â\x99\',"\'").str.replace(\'Ã¢Â\x80Â\x99\',"\'").str.replace("Ã¢Â\x80Â\x98","").str.replace("Ã¢Â\x80Â\x9c","").str.replace("Ã¢Â\x80Â\x9d","")\nmodified_clean_address = modified_clean_address.str.replace("hN", "h N")\nprint(modified_clean_address[0])\nmodified_clean_address = modified_clean_address.str.replace(".5 ", " ")\nprint(modified_clean_address[0])\nmodified_clean_address = modified_clean_address.str.replace(",h ", ", h ")\nprint(modified_clean_address[0])\nmodified_clean_address = modified_clean_address.str.replace(",h", ", h ")\nprint(modified_clean_address[0])\nmodified_clean_address = modified_clean_address.str.replace(", h.", ", h. ")\nprint(modified_clean_address[0])\nmodified_clean_address = modified_clean_address.str.replace(", h .", ", h. ")\nprint(modified_clean_address[0])\nmodified_clean_address = modified_clean_address.str.replace("H udson", "Hudson")\nmodified_clean_address = modified_clean_address.str.replace("\'wav", "\'way")\nmodified_clean_address = modified_clean_address.str.replace("B\'way", "Broadway")\nmodified_clean_address = modified_clean_address.str.replace("B way", "Broadway")\nmodified_clean_address = modified_clean_address.str.replace("B\'kly n", "B\'klyn")\nmodified_clean_address = modified_clean_address.str.replace(",n", " n")\nmodified_clean_address = modified_clean_address.str.replace("W.h", " Wh")\nmodified_clean_address = modified_clean_address.str.replace("h-", " h ")\nmodified_clean_address = modified_clean_address.str.replace("h-", " h ")\nmodified_clean_address = modified_clean_address.str.replace("-h.", "h.")\n#modified_clean_address = modified_clean_address.str.replace("H()", "h.")\n#modified_clean_address = modified_clean_address.str.replace("*", " ")\n#modified_clean_address = modified_clean_address.str.replace("h r.", "h r")\n\n#modified_clean_address = modified_clean_address.str.replace(".h", ", h.")\n\n#modified_clean_address = modified_clean_address.str.replace("^h", "  h")\n#modified_clean_address = modified_clean_address.str.replace("h*", "  h ")\n\n#modified_clean_address = modified_clean_address.str.replace(". .", " ")\n'

In [10]:
for i in range(0,len(modified_clean_address)):
    if str(modified_clean_address[i]) == 'nan':
        print(i, modified_clean_address[i])
        modified_clean_address[i] = ''

340 nan
818 nan
1163 nan
1175 nan
1547 nan
1564 nan
2241 nan
2767 nan
2985 nan
3033 nan
3102 nan
3561 nan
4886 nan
6605 nan
6826 nan
7404 nan
7421 nan
7755 nan
7776 nan
7794 nan
8237 nan
8526 nan
8917 nan
9106 nan
9159 nan
9190 nan
9286 nan
9632 nan
10217 nan
10279 nan
10465 nan
10487 nan
10771 nan
10791 nan
11049 nan
11066 nan
11098 nan
11340 nan
11360 nan
11396 nan
11415 nan
11499 nan
11949 nan
12068 nan
12124 nan
12135 nan
12137 nan
12190 nan
12370 nan
12515 nan
12668 nan
12772 nan
13155 nan
13256 nan
13369 nan
13470 nan
13493 nan
13579 nan
13587 nan
13614 nan
13615 nan
13733 nan
13756 nan
14076 nan
14315 nan
14337 nan
14358 nan
14488 nan
14553 nan
14556 nan
14589 nan
14648 nan
14650 nan
14693 nan
14701 nan
14898 nan
15174 nan
15243 nan
15249 nan
15272 nan
15505 nan
15513 nan
15819 nan
16061 nan
16083 nan
16242 nan
16321 nan
16517 nan
16786 nan
16821 nan
17049 nan
17057 nan
17102 nan
17221 nan
17239 nan
17368 nan
17396 nan
17399 nan
17516 nan
17535 nan
17568 nan
17619 nan
17780 nan
17843 nan
17951 nan
18337 nan
18358 nan
18362 nan
18379 nan
18471 nan
18571 nan
18619 nan
18622 nan
18653 nan
18655 nan
18679 nan
18768 nan
18811 nan
18822 nan
18849 nan
19033 nan
19048 nan
19068 nan
19122 nan
19137 nan
19511 nan
19514 nan
20189 nan
20218 nan
20306 nan
20361 nan
20472 nan
20501 nan
20716 nan
20724 nan
20733 nan
20768 nan
21023 nan
21024 nan
21049 nan
21053 nan
21156 nan
21195 nan
21756 nan
21852 nan
22327 nan
22587 nan
22588 nan
22772 nan
22779 nan
22885 nan
22919 nan
22934 nan
22953 nan
22988 nan
23366 nan
23379 nan
23395 nan
23398 nan
24094 nan
24102 nan
24457 nan
24626 nan
24633 nan
24634 nan
24699 nan
24731 nan
25046 nan
25074 nan
25075 nan
25208 nan
25214 nan
25231 nan
25320 nan
25539 nan
25631 nan
25972 nan
26010 nan
26127 nan
26158 nan
26238 nan
26254 nan
26261 nan
26290 nan
26307 nan
26537 nan
26606 nan
26875 nan
26877 nan
27142 nan
27713 nan
27741 nan
27776 nan
27844 nan
27872 nan
27889 nan
27904 nan
28060 nan
28090 nan
28165 nan
28182 nan
28430 nan
28455 nan
28508 nan
28576 nan
28580 nan
28744 nan
28837 nan
28870 nan
28899 nan
28997 nan
29045 nan
29150 nan
29372 nan
29715 nan
29902 nan
29917 nan
30102 nan
30104 nan
30198 nan
30222 nan
30239 nan
30375 nan
30545 nan
31144 nan
31163 nan
31181 nan
31473 nan
31479 nan
31517 nan
31846 nan
31989 nan
32023 nan
32145 nan
32183 nan
32205 nan
32306 nan
32310 nan
32435 nan
32615 nan
32629 nan
32653 nan
32838 nan
32990 nan
33083 nan
33101 nan
33252 nan
33512 nan
33595 nan
33793 nan
34001 nan
34016 nan
34155 nan
34174 nan
34181 nan
34185 nan
34189 nan
34207 nan
34218 nan
34242 nan
34246 nan
34248 nan
34251 nan
34260 nan
34263 nan
34341 nan
34345 nan
34357 nan
34359 nan
34365 nan
34370 nan
34376 nan
34384 nan
34390 nan
34395 nan
34457 nan
34660 nan
34694 nan
34724 nan
34993 nan
35007 nan
35382 nan
35465 nan
35685 nan
35707 nan
35897 nan
35931 nan
35938 nan
35948 nan
35970 nan
35981 nan
35985 nan
35987 nan
35994 nan
36215 nan
36333 nan
36680 nan
36700 nan
36785 nan
36935 nan
37130 nan
37132 nan
37153 nan
37158 nan
37167 nan
37175 nan
37197 nan
37200 nan
37281 nan
37305 nan
37334 nan
37360 nan
37456 nan
37516 nan
37931 nan
37949 nan
37957 nan
37978 nan
37999 nan
38005 nan
38065 nan
38090 nan
38118 nan
38120 nan
38140 nan
38199 nan
38699 nan
38985 nan
39002 nan
39359 nan
39367 nan
41628 nan
41671 nan
42051 nan
42186 nan
43077 nan
43085 nan
43196 nan
43213 nan
43257 nan
43273 nan
43336 nan
43531 nan
43742 nan
43749 nan
44134 nan
44302 nan
44371 nan
44386 nan
44421 nan
44440 nan
44467 nan
44472 nan
44559 nan
44790 nan
44820 nan
44833 nan
44972 nan
45065 nan
45117 nan
45760 nan
46124 nan
46136 nan
46207 nan
46247 nan
46254 nan
46446 nan
46508 nan
46512 nan
46769 nan
46885 nan
46899 nan
46947 nan
46979 nan
47180 nan
47200 nan
47224 nan
47237 nan
47523 nan
47888 nan
48171 nan
48195 nan
48412 nan
48982 nan
49027 nan
49511 nan
49558 nan
50019 nan
50650 nan
51708 nan
51885 nan
51897 nan
51912 nan
51972 nan
51987 nan
52201 nan
52217 nan
52811 nan
52978 nan
53005 nan
53315 nan
53354 nan
53365 nan
53402 nan
53459 nan
53545 nan
53549 nan
53559 nan
53667 nan
53681 nan
53698 nan
53701 nan
53721 nan
53727 nan
53895 nan
53897 nan
53922 nan
54020 nan
54037 nan
54054 nan
54202 nan
54231 nan
54283 nan
54442 nan
54568 nan
54737 nan
55602 nan
55603 nan
55605 nan
55626 nan
55862 nan
55973 nan
56029 nan
56051 nan
56071 nan
56132 nan
56142 nan
56195 nan
56235 nan
56472 nan
56485 nan
56541 nan
57101 nan
57254 nan
57344 nan
57351 nan
57354 nan
57356 nan
57382 nan
57388 nan
57403 nan
57419 nan
57438 nan
57442 nan
57445 nan
57451 nan
57512 nan
58083 nan
58422 nan
58498 nan
58571 nan
58637 nan
59056 nan
59240 nan
59270 nan
59320 nan
59347 nan
59482 nan
59551 nan
59614 nan
59626 nan
59627 nan
59648 nan
59698 nan
59699 nan
59719 nan
59726 nan
59782 nan
59788 nan
59801 nan
60481 nan
60655 nan
60659 nan
60687 nan
60690 nan
60696 nan
61138 nan
61143 nan
61180 nan
61238 nan
61335 nan
61562 nan
61751 nan
61839 nan
61979 nan
62013 nan
62250 nan
62269 nan
62327 nan
62345 nan
62432 nan
62436 nan
62444 nan
62445 nan
62654 nan
63060 nan
63543 nan
63559 nan
63588 nan
63631 nan
63652 nan
63737 nan
64104 nan
64164 nan
64214 nan
64243 nan
64390 nan
64528 nan
64536 nan
64626 nan
64745 nan
64815 nan
65130 nan
65153 nan
65181 nan
65448 nan
65452 nan
65489 nan
65498 nan
65954 nan
66008 nan
66021 nan
66269 nan
66586 nan
66861 nan
66979 nan
66988 nan
67009 nan
67026 nan
67033 nan
67039 nan
67235 nan
68293 nan
68295 nan
68486 nan
68492 nan
68511 nan
68513 nan
68522 nan
68523 nan
68552 nan
68612 nan
68622 nan
68634 nan
68794 nan
69177 nan
69204 nan
69397 nan
69594 nan
69663 nan
69703 nan
69780 nan
69797 nan
69946 nan
70123 nan
70167 nan
70205 nan
70207 nan
70219 nan
70228 nan
70229 nan
70376 nan
70954 nan
71054 nan
71121 nan
71157 nan
71179 nan
71190 nan
71589 nan
71603 nan
71617 nan
71700 nan
71818 nan
71819 nan
71871 nan
72166 nan
72242 nan
72425 nan
72498 nan
72542 nan
72573 nan
72860 nan
72907 nan
72917 nan
72924 nan
72953 nan
72956 nan
72970 nan
74341 nan
74905 nan
74942 nan
75022 nan
75534 nan
75642 nan
75824 nan
75882 nan
75909 nan
76147 nan
76199 nan
76204 nan
76205 nan
76206 nan
76207 nan
76208 nan
76209 nan
76211 nan
76214 nan
76217 nan
76218 nan
76221 nan
76223 nan
76229 nan
76240 nan
76241 nan
76243 nan
76245 nan
76253 nan
76261 nan
76267 nan
76276 nan
76286 nan
76289 nan
76297 nan
76307 nan
76313 nan
76315 nan
76331 nan
76332 nan
76335 nan
76338 nan
76339 nan
76341 nan
76345 nan
76346 nan
76356 nan
76364 nan
76378 nan
76382 nan
76387 nan
76388 nan
76389 nan
76391 nan
76395 nan
76396 nan
76400 nan
76406 nan
76417 nan
76421 nan
76424 nan
76429 nan
76431 nan
76436 nan
76447 nan
76452 nan
76453 nan
76464 nan
76467 nan
76468 nan
76470 nan
76471 nan
76472 nan
76475 nan
76480 nan
76484 nan
76485 nan
76488 nan
76490 nan
76491 nan
76492 nan
76496 nan
76497 nan
76501 nan
76512 nan
76517 nan
76529 nan
76530 nan
76539 nan
76541 nan
76545 nan
76548 nan
76554 nan
76557 nan
76560 nan
76562 nan
76577 nan
76580 nan
76581 nan
76584 nan
76588 nan
76600 nan
76618 nan
76623 nan
76625 nan
76630 nan
76636 nan
76641 nan
76644 nan
76647 nan
76656 nan
76662 nan
76664 nan
76667 nan
76676 nan
76682 nan
76690 nan
76698 nan
76702 nan
76708 nan
76711 nan
76713 nan
76725 nan
76732 nan
76736 nan
76737 nan
76746 nan
76755 nan
76757 nan
76761 nan
76764 nan
76768 nan
76777 nan
76786 nan
76787 nan
76789 nan
76792 nan
76799 nan
76804 nan
76805 nan
76807 nan
76808 nan
76813 nan
76814 nan
76815 nan
76827 nan
76828 nan
76830 nan
76832 nan
76833 nan
76834 nan
76837 nan
76844 nan
76851 nan
76852 nan
76856 nan
76858 nan
76859 nan
76868 nan
76873 nan
76879 nan
76880 nan
76881 nan
76882 nan
76884 nan
76886 nan
76894 nan
76901 nan
76903 nan
76909 nan
76914 nan
76919 nan
76922 nan
76936 nan
76949 nan
76956 nan
76962 nan
76968 nan
76973 nan
76976 nan
76978 nan
76980 nan
76981 nan
76983 nan
76984 nan
76992 nan
76999 nan
77003 nan
77005 nan
77019 nan
77021 nan
77033 nan
77039 nan
77046 nan
77052 nan
77056 nan
77057 nan
77059 nan
77065 nan
77069 nan
77070 nan
77084 nan
77091 nan
77092 nan
77096 nan
77097 nan
77098 nan
77099 nan
77101 nan
77106 nan
77114 nan
77117 nan
77119 nan
77131 nan
77135 nan
77137 nan
77140 nan
77141 nan
77146 nan
77159 nan
77164 nan
77165 nan
77173 nan
77179 nan
77190 nan
77198 nan
77204 nan
77206 nan
77213 nan
77221 nan
77222 nan
77230 nan
77232 nan
77234 nan
77237 nan
77242 nan
77251 nan
77252 nan
77254 nan
77260 nan
77265 nan
77269 nan
77270 nan
77277 nan
77283 nan
77284 nan
77301 nan
77308 nan
77316 nan
77317 nan
77321 nan
77325 nan
77326 nan
77336 nan
77339 nan
77340 nan
77343 nan
77344 nan
77345 nan
77346 nan
77349 nan
77362 nan
77369 nan
77370 nan
77373 nan
77383 nan
77396 nan
77412 nan
77413 nan
77419 nan
77425 nan
77426 nan
77431 nan
77434 nan
77443 nan
77458 nan
77464 nan
77477 nan
77486 nan
77501 nan
77510 nan
77513 nan
77522 nan
77527 nan
77528 nan
77530 nan
77532 nan
77548 nan
77549 nan
77551 nan
77553 nan
77561 nan
77569 nan
77575 nan
77584 nan
77594 nan
77597 nan
77605 nan
77615 nan
77621 nan
77623 nan
77639 nan
77640 nan
77643 nan
77646 nan
77647 nan
77649 nan
77653 nan
77654 nan
77664 nan
77672 nan
77686 nan
77690 nan
77695 nan
77696 nan
77697 nan
77699 nan
77703 nan
77704 nan
77708 nan
77714 nan
77725 nan
77729 nan
77732 nan
77737 nan
77739 nan
77744 nan
77755 nan
77760 nan
77761 nan
77772 nan
77775 nan
77776 nan
77778 nan
77779 nan
77780 nan
77783 nan
77788 nan
77792 nan
77793 nan
77796 nan
77798 nan
77799 nan
77800 nan
77804 nan
77805 nan
77809 nan
77820 nan
77825 nan
77837 nan
77838 nan
77847 nan
77849 nan
77853 nan
77856 nan
77862 nan
77865 nan
77868 nan
77870 nan
77885 nan
77888 nan
77889 nan
77892 nan
77896 nan
77908 nan
77926 nan
77931 nan
77933 nan
77938 nan
77944 nan
77949 nan
77952 nan
77955 nan
77964 nan
77970 nan
77972 nan
77975 nan
77984 nan
77990 nan
77998 nan
78006 nan
78010 nan
78016 nan
78019 nan
78021 nan
78033 nan
78040 nan
78044 nan
78045 nan
78054 nan
78063 nan
78065 nan
78069 nan
78072 nan
78076 nan
78085 nan
78094 nan
78095 nan
78097 nan
78100 nan
78107 nan
78112 nan
78113 nan
78115 nan
78116 nan
78121 nan
78122 nan
78123 nan
78135 nan
78136 nan
78138 nan
78140 nan
78141 nan
78142 nan
78145 nan
78152 nan
78159 nan
78160 nan
78164 nan
78166 nan
78167 nan
78176 nan
78181 nan
78187 nan
78188 nan
78189 nan
78190 nan
78192 nan
78194 nan
78202 nan
78209 nan
78211 nan
78217 nan
78222 nan
78227 nan
78230 nan
78244 nan
78257 nan
78264 nan
78270 nan
78276 nan
78281 nan
78284 nan
78286 nan
78288 nan
78289 nan
78291 nan
78292 nan
78300 nan
78307 nan
78311 nan
78313 nan
78327 nan
78329 nan
78341 nan
78347 nan
78354 nan
78360 nan
78364 nan
78365 nan
78367 nan
78373 nan
78377 nan
78378 nan
78392 nan
78399 nan
78400 nan
78404 nan
78405 nan
78406 nan
78407 nan
78409 nan
78414 nan
78422 nan
78425 nan
78427 nan
78439 nan
78443 nan
78445 nan
78448 nan
78449 nan
78454 nan
78467 nan
78472 nan
78473 nan
78481 nan
78487 nan
78498 nan
78506 nan
78512 nan
78514 nan
78521 nan
78529 nan
78530 nan
78538 nan
78540 nan
78542 nan
78545 nan
78550 nan
78559 nan
78560 nan
78562 nan
78568 nan
78573 nan
78577 nan
78578 nan
78585 nan
78591 nan
78592 nan
78609 nan
78616 nan
78624 nan
78625 nan
78629 nan
78633 nan
78634 nan
78644 nan
78655 nan
78678 nan
78686 nan
78688 nan
78690 nan
78702 nan
78704 nan
78709 nan
78711 nan
78715 nan
78718 nan
78721 nan
78734 nan
78735 nan
78738 nan
78743 nan
78744 nan
78753 nan
78755 nan
78756 nan
78764 nan
78779 nan
78782 nan
78796 nan
78798 nan
78799 nan
78802 nan
78803 nan
78805 nan
78806 nan
78809 nan
78820 nan
78830 nan
78861 nan
78866 nan
78867 nan
78872 nan
78884 nan
78890 nan
78891 nan
78892 nan
78893 nan
78908 nan
78910 nan
78923 nan
78924 nan
78925 nan
78927 nan
78932 nan
78933 nan
78940 nan
78947 nan
78953 nan
78958 nan
78965 nan
78969 nan
78974 nan
78975 nan
78978 nan
78980 nan
78981 nan
78982 nan
78990 nan
78991 nan
78994 nan
79004 nan
79005 nan
79010 nan
79018 nan
79024 nan
79027 nan
79028 nan
79031 nan
79045 nan
79058 nan
79059 nan
79060 nan
79061 nan
79064 nan
79065 nan
79067 nan
79075 nan
79076 nan
79080 nan
79081 nan
79091 nan
79098 nan
79100 nan
79105 nan
79112 nan
79113 nan
79117 nan
79129 nan
79136 nan
79137 nan
79138 nan
79139 nan
79141 nan
79143 nan

79145 nan
79146 nan
79147 nan
79150 nan
79151 nan
79152 nan
79154 nan
79160 nan
79171 nan
79172 nan
79174 nan
79177 nan
79178 nan
79180 nan
79184 nan
79189 nan
79191 nan
79194 nan
79195 nan
79202 nan
79203 nan
79204 nan
79216 nan
79225 nan
79226 nan
79229 nan
79230 nan
79231 nan
79232 nan
79235 nan
79236 nan
79255 nan
79258 nan
79259 nan
79260 nan
79281 nan
79283 nan
79288 nan
79291 nan
79300 nan
79303 nan
79307 nan
79311 nan
79317 nan
79318 nan
79319 nan
79320 nan
79328 nan
79329 nan
79330 nan
79335 nan
79338 nan
79342 nan
79355 nan
79359 nan
79371 nan
79376 nan
79386 nan
79390 nan
79398 nan
79399 nan
79400 nan
79402 nan
79405 nan
79407 nan
79422 nan
79424 nan
79428 nan
79430 nan
79440 nan
79444 nan
79450 nan
79451 nan
79452 nan
79454 nan
79457 nan
79459 nan
79462 nan
79467 nan
79469 nan
79474 nan
79475 nan
79480 nan
79487 nan
79504 nan
79506 nan
79510 nan
79517 nan
79518 nan
79520 nan
79523 nan
79528 nan
79539 nan
79540 nan
79543 nan
79549 nan
79567 nan
79575 nan
79576 nan
79579 nan
79588 nan
79591 nan
79592 nan
79604 nan
79605 nan
79606 nan
79614 nan
79617 nan
79619 nan
79620 nan
79623 nan
79626 nan
79627 nan
79629 nan
79637 nan
79644 nan
79645 nan
79653 nan
79655 nan
79670 nan
79671 nan
79672 nan
79673 nan
79674 nan
79675 nan
79681 nan
79683 nan
79697 nan
79701 nan
79702 nan
79703 nan
79704 nan
79710 nan
79711 nan
79715 nan
79716 nan
79718 nan
79722 nan
79735 nan
79741 nan
79742 nan
79744 nan
79745 nan
79749 nan
79754 nan
79757 nan
79771 nan
79775 nan
79787 nan
79788 nan
79791 nan
79793 nan
79800 nan
79814 nan
79824 nan
79834 nan
79844 nan
79854 nan
79855 nan
79862 nan
79868 nan
79877 nan
79879 nan
79886 nan
79890 nan
79898 nan
79900 nan
79903 nan
79904 nan
79917 nan
79919 nan
79921 nan
79924 nan
79926 nan
79928 nan
79945 nan
79948 nan
79962 nan
79965 nan
79968 nan
79975 nan
79978 nan
79981 nan
79986 nan
79989 nan
79997 nan
79999 nan
80003 nan
80006 nan
80007 nan
80010 nan
80014 nan
80015 nan
80016 nan
80023 nan
80024 nan
80030 nan
80033 nan
80047 nan
80050 nan
80053 nan
80055 nan
80065 nan
80075 nan
80086 nan
80089 nan
80096 nan
80099 nan
80100 nan
80101 nan
80103 nan
80104 nan
80105 nan
80106 nan
80107 nan
80111 nan
80114 nan
80115 nan
80116 nan
80125 nan
80128 nan
80129 nan
80134 nan
80138 nan
80141 nan
80144 nan
80148 nan
80153 nan
80161 nan
80167 nan
80175 nan
80177 nan
80183 nan
80186 nan
80205 nan
80207 nan
80209 nan
80217 nan
80225 nan
80226 nan
80249 nan
80255 nan
80270 nan
80279 nan
80280 nan
80299 nan
80305 nan
80335 nan
80340 nan
80347 nan
80350 nan
80356 nan
80359 nan
80360 nan
80364 nan
80369 nan
80378 nan
80385 nan
80386 nan
80391 nan
80398 nan
80399 nan
80403 nan
80407 nan
80412 nan
80414 nan
80416 nan
80421 nan
80425 nan
80426 nan
80435 nan
80441 nan
80443 nan
80445 nan
80450 nan
80451 nan
80468 nan
80470 nan
80472 nan
80480 nan
80487 nan
80491 nan
80494 nan
80502 nan
80504 nan
80512 nan
80517 nan
80518 nan
80526 nan
80531 nan
80534 nan
80536 nan
80540 nan
80547 nan
80553 nan
80554 nan
80556 nan
80557 nan

In [11]:
for i in range(0,len(modified_clean_address)):
        if modified_clean_address[i].find("E.") >= 0:
            modified_clean_address[i] = modified_clean_address[i].replace('E.','E ').replace('  ', ' ')

In [12]:
for i in range(0,len(modified_clean_address)):
    if modified_clean_address[i].find("W.") >= 0:
        modified_clean_address[i] = modified_clean_address[i].replace('W.','W ').replace('  ', ' ')

In [13]:
for i in range(0,len(modified_clean_address)):
    if modified_clean_address[i].find(".h") >= 0:
        modified_clean_address[i] = modified_clean_address[i].replace('.h',', h. ').replace(',,',',').replace('  ',' ')

In [14]:
for i in range(0,len(modified_clean_address)):
    if modified_clean_address[i].find(",c") >= 0:
        modified_clean_address[i] = modified_clean_address[i].replace(',c',' c')

In [15]:
for i in range(0,len(modified_clean_address)):
    if modified_clean_address[i].find(" c. ") >= 0:
        modified_clean_address[i] = modified_clean_address[i].replace('c.','c')

In [16]:
for i in range(0,len(modified_clean_address)):
    if modified_clean_address[i].find(" n. ") >= 0:
        modified_clean_address[i] = modified_clean_address[i].replace(' n. ',' n ')

In [17]:
for i in range(0,len(modified_clean_address)):
    if modified_clean_address[i].find("h r ") >=0:
        modified_clean_address[i] = modified_clean_address[i].replace('h r','h. rear').replace('rear.','rear ')

In [18]:
for i in range(0,len(modified_clean_address)):
    if modified_clean_address[i].find("h. r ") >=0:
        modified_clean_address[i] = modified_clean_address[i].replace('h. r','h. rear').replace('rear.','rear ')

In [19]:
for i in range(0,len(modified_clean_address)):
    if modified_clean_address[i][0:2].find("h'") >=0:
        modified_clean_address[i] = modified_clean_address[i].replace("h'","h. ")

In [20]:
for i in range(0,len(modified_clean_address)):
    if modified_clean_address[i][0:2].find("th") >=0:
        modified_clean_address[i] = modified_clean_address[i].replace("th","h")

In [21]:
modified_clean_address[0]

'39 Pearl'

In [22]:
#re.findall(r'. 1', '.1')

In [23]:
import re

modified_clean_address4 = []
intersections_n_1 = []
intersections_n_2 = []

intersections_c_1 = []
intersections_c_2 = []

for i in range(0,len(modified_clean_address)):
    temp = modified_clean_address[i]
    
    
    
    
    """
    string_with_th = re.findall(r'[0-9]+th', temp)
    for j in range (0, len(string_with_th)):
        temp = temp.replace(string_with_th[j], string_with_th[j].replace('th',''))
    
    string_with_d = re.findall(r'[0-9]+d', temp)
    for j in range (0, len(string_with_d)):
        temp = temp.replace(string_with_d[j], string_with_d[j].replace('d',''))
    
    string_with_rd = re.findall(r'[0-9]+rd', temp)
    for j in range (0, len(string_with_rd)):
        temp = temp.replace(string_with_rd[j], string_with_rd[j].replace('rd',''))
    
    string_with_st = re.findall(r'[0-9]+st', temp)
    for j in range (0, len(string_with_st)):
        temp = temp.replace(string_with_st[j], string_with_st[j].replace('st',''))
    
    string_with_h_dot = re.findall(r'h.+[0-9]', temp)
    for j in range (0, len(string_with_h_dot)):
        temp = temp.replace(string_with_h_dot[j], string_with_h_dot[j].replace('h.','h. ').replace('  ',' '))
    
    string_with_h = re.findall(r'h+[0-9]', temp)
    for j in range (0, len(string_with_h)):
        temp = temp.replace(string_with_h[j], string_with_h[j].replace('h','h ').replace('  ',' '))
        
    string_with_fullstop = re.findall(r'. +[0-9]', temp)
    for j in range (0, len(string_with_fullstop)):
        temp = temp.replace(string_with_fullstop[j], string_with_fullstop[j].replace('.','. h ').replace('  ',' '))
    
    string_with_comma = re.findall(r', +[0-9]', temp)
    for j in range (0, len(string_with_comma)):
        temp = temp.replace(string_with_comma[j], string_with_comma[j].replace(',',', h ').replace('  ',' '))
    
    string_with_bracket = re.findall(r'\) +[0-9]', temp)
    for j in range (0, len(string_with_bracket)):
        temp = temp.replace(string_with_bracket[j], string_with_bracket[j].replace(')',') h ').replace('  ',' '))
    
    string_with_dash = re.findall(r'-+[0-9]', temp)
    for j in range (0, len(string_with_dash)):
        temp = temp.replace(string_with_dash[j], string_with_dash[j].replace('-','').replace('  ',' '))
    
    string_with_fullstop_number = re.findall(r'.+[0-9]', temp)
    for j in range (0, len(string_with_fullstop_number)):
        temp = temp.replace(string_with_fullstop_number[j], string_with_fullstop_number[j].replace('.','').replace('  ',' '))
    
    
    string_with_S_1 = re.findall(r'[0-9]+S', temp)
    string_with_S_2 = re.findall(r'S+[0-9]', temp)
    string_with_S = string_with_S_1 + string_with_S_2
    for j in range (0, len(string_with_S)):
        #print(i,string_with_S)
        temp = temp.replace(string_with_S[j], string_with_S[j].replace('S','5'))
        #print(temp)
    
    
    """
    
    
    
    try:
        location_of_h_1 = temp.split().index('h.')
    except:
        location_of_h_1 = -1
    try:
        location_of_h_2 = temp.split().index('h')
    except:
        location_of_h_2 = -1
    #print(location_of_h_1, location_of_h_2)

    location_of_h = max(location_of_h_1, location_of_h_2)
    """
    if location_of_h_1>0:
        if location_of_h_2<0:
            location_of_h = location_of_h_1
        else:
            #print(i,'in exception1')
            #print(location_of_h_1, location_of_h_2)
            location_of_h = max(location_of_h_1, location_of_h_2)
    
    else:
        if location_of_h_2 > 0:
            location_of_h = location_of_h_2
        else:
            print(i,'in exception2')
            print(location_of_h_1, location_of_h_2)
            location_of_h = -1
    """
    temp = temp.replace('^','')
    
    
    
    """
    temp = temp.replace('ft.','')
    temp = temp.replace('ft','')
    temp = temp.replace('Ft.','')
    """
    
    undesired_starts = ['.',' .',',',' ,','-',' -','- ',', ','. ',"'","' "," '","''",'&','*','& ','* ',
                       ' &',' *']
    for i in range(0,len(undesired_starts)):
        if temp[0:2].find(undesired_starts[i])>=0:
            temp = temp[0:2].replace(undesired_starts[i],'') + temp[2:]
    
    words_after_h = temp.split()[location_of_h+1:]
    try:
        location_of_n = words_after_h.index('n')
        intersection_n_street1 = ' '.join(words_after_h[0:location_of_n])
        intersection_n_street2 = ' '.join(words_after_h[location_of_n+1:])

        intersections_n_1.append(intersection_n_street1)
        intersections_n_2.append(intersection_n_street2)
    except:
        intersections_n_1.append('')
        intersections_n_2.append('')
    
    try:
        location_of_c = words_after_h.index('c')
        intersection_c_street1 = ' '.join(words_after_h[0:location_of_c])
        intersection_c_street2 = ' '.join(words_after_h[location_of_c+1:])

        intersections_c_1.append(intersection_c_street1)
        intersections_c_2.append(intersection_c_street2)
    except:
        intersections_c_1.append('')
        intersections_c_2.append('')
    
    modified_clean_address4.append(temp)

In [24]:
#for i in range(0,len(intersections_c_1)):
    #print(i, intersections_c_1[i] + ' and ' + intersections_c_2[i])

In [25]:
for i in range(0,len(modified_clean_address4)):
    if modified_clean_address4[i].find(".h") >= 0:
        print(i, modified_clean_address4[i])

In [26]:
#for i in range(0,len(modified_clean_address)):
    #if modified_clean_address[i].find(" n ") >0:
        #print(i, modified_clean_address[i])

In [27]:
df['modified_clean_address'] = modified_clean_address4

In [28]:
df['n_street1'] = intersections_n_1
df['n_street2'] = intersections_n_2
df['c_street1'] = intersections_c_1
df['c_street2'] = intersections_c_2

In [29]:
#df.head()

In [30]:
#df.to_excel('doubt/not so confident2.xlsx')

In [31]:
df_modified_addresses = pd.DataFrame(modified_clean_address4, columns=['clean_address'])

In [32]:
#pd.DataFrame(modified_clean_address2).to_csv('doubt/doubt2.txt', header=None,  sep=' ', mode='a')

In [33]:
temp_addr = []
for i in range(0,len(df_modified_addresses)):
    temp_addr.append(str(i)+" "+df_modified_addresses['clean_address'][i])
#np.savetxt('doubt/not so confident addr.txt', temp_addr, fmt='%s')

In [34]:
#np.savetxt('doubt/not so confident addr.txt', temp_addr, fmt='%s')

In [35]:
#df.head()

In [36]:
#df.columns

In [37]:
#df.head()

In [38]:
df['n_street1'] = df['n_street1'].replace('',np.nan)
df['n_street2'] = df['n_street2'].replace('',np.nan)
df['c_street1'] = df['c_street1'].replace('',np.nan)
df['c_street2'] = df['c_street2'].replace('',np.nan)

In [39]:
#df['filter11'] = np.where(df['n_street1'].isna() & df['n_street2'].isna() & df['c_street1'].isna() & df['c_street2'].isna() & df['new h house number'].isna() & df['new h street name'].isna(), 1, 0)
#was initially uncommented

df['filter11'] = np.where(df['n_street1'].isna() & df['n_street2'].isna() & df['c_street1'].isna() & df['c_street2'].isna(), 1, 0)

In [40]:
df_filter11 = df.loc[df['filter11'] == 1]
df_filter11 = df_filter11.reset_index()

In [41]:
#df_filter11['modified_clean_address']

In [42]:
modified_clean_address5 = []
for i in range(0,len(df_filter11)):
    temp = df_filter11['modified_clean_address'][i]
    
    string_with_S = re.findall(r'[0-9]+S', temp)
    for i in range (0, len(string_with_S)):
        temp = temp.replace(string_with_S[i], string_with_S[i].replace('S','5'))
    modified_clean_address5.append(temp)

In [43]:
#for i in range(0,len(modified_clean_address5)):
    #print(i, modified_clean_address5[i])

In [44]:
#for i in range(0,len(modified_clean_address5)):
    #if modified_clean_address5[i].find("h. ") <0:
        #print(i, modified_clean_address5[i])

In [45]:
df['modified_clean_address'][10:16]

10      175 Canal
11    137 Norfolk
12        53 Av D
13       5 Ludlow
14         1 Av D
15     Morrisania
Name: modified_clean_address, dtype: object

In [46]:
df['modified_clean_address'] = df['modified_clean_address'].str.replace('rearear','rear')
df['modified_clean_address'] = df['modified_clean_address'].str.replace('rearefused','refused')
df['modified_clean_address'] = df['modified_clean_address'].str.replace('h. r ','h. rear ')

In [47]:
df

,Unnamed: 0,Unnamed: 0.1,Full Name,First Name,Last Name,Middle Name,Widow-flag,Widow Of,Title,Occupation,...,Address 2 City,Full Address,part after and,part before h,modified_clean_address,n_street1,n_street2,c_street1,c_street2,filter11
0,0,0,Ackley Addison,Addison,Ackley,NaN,False,NaN,NaN,clerk,...,NaN,39 Pearl,NaN,47,39 Pearl,NaN,NaN,NaN,NaN,1
1,1,1,Adams William,William,Adams,NaN,False,NaN,NaN,weigher,...,NaN,170 Clinton Brooklyn,NaN,20 Washington & 13,170 Clinton Brooklyn,NaN,NaN,NaN,NaN,1
2,2,2,Aitkin Thomas,Thomas,Aitkin,NaN,False,NaN,NaN,stonecutter,...,NaN,601 Washington,NaN,NaN,601 Washington,NaN,NaN,NaN,NaN,1
3,3,3,Albro Benjamin,Benjamin,Albro,NaN,False,NaN,NaN,sen,...,NaN,328 Bowery,NaN,NaN,328 Bowery,NaN,NaN,NaN,NaN,1
4,4,4,Allen E . W,E,Allen,.,False,NaN,NaN,publisher,...,NaN,42 Orange,NaN,NaN,42 Orange,NaN,NaN,NaN,NaN,1
5,5,5,Anderson Frederick R,Frederick,Anderson,R,False,NaN,NaN,mer,...,NaN,77 Barrow,NaN,13,77 Barrow,NaN,NaN,NaN,NaN,1
6,6,6,Anderson John R,John,Anderson,R,False,NaN,NaN,seaman,...,NaN,586 E 4th,NaN,NaN,586 E 4th,NaN,NaN,NaN,NaN,1
7,7,7,Anthes Peter,Peter,Anthes,NaN,False,NaN,NaN,NaN,...,NaN,34 Av C,NaN,NaN,34 Av C,NaN,NaN,NaN,NaN,1
8,8,8,Anthes & Eckardt,&,Anthes,Eckardt,False,NaN,NaN,barbers,...,NaN,34 Av C,NaN,NaN,34 Av C,NaN,NaN,NaN,NaN,1
9,9,9,Appell John,John,Appell,NaN,False,NaN,NaN,tailor,...,NaN,40 Av C,NaN,NaN,40 Av C,NaN,NaN,NaN,NaN,1
10,10,10,Arcularius Jacob S,Jacob,Arcularius,S,False,NaN,NaN,NaN,...,NaN,175 Canal,NaN,h 175,175 Canal,NaN,NaN,NaN,NaN,1
11,11,11,Arenfred George,George,Arenfred,NaN,False,NaN,NaN,NaN,...,NaN,137 Norfolk,NaN,NaN,137 Norfolk,NaN,NaN,NaN,NaN,1
12,12,12,Armstrong George,George,Armstrong,NaN,False,NaN,NaN,shoemaker,...,NaN,53 Av D,NaN,NaN,53 Av D,NaN,NaN,NaN,NaN,1
13,13,13,Armstrong John D,John,Armstrong,D,False,NaN,NaN,coachmaker,...,NaN,5 Ludlow,NaN,NaN,5 Ludlow,NaN,NaN,NaN,NaN,1
14,14,14,Arnold Henry,Henry,Arnold,NaN,False,NaN,NaN,drygoods,...,NaN,1 Av D,NaN,1 Av,1 Av D,NaN,NaN,NaN,NaN,1
15,15,15,Ash William A,William,Ash,A,False,NaN,NaN,way,...,NaN,Morrisania,NaN,413,Morrisania,NaN,NaN,NaN,NaN,1
16,16,16,Auchincloss John T,John,Auchincloss,T,False,NaN,NaN,mer,...,NaN,7 Murray,NaN,192,7 Murray,NaN,NaN,NaN,NaN,1
17,17,17,Auchincloss & Croxon,&,Auchincloss,Croxon,False,NaN,NaN,mers,...,NaN,192 Fulton,NaN,NaN,192 Fulton,NaN,NaN,NaN,NaN,1
18,18,18,Bagley William,William,Bagley,NaN,False,NaN,NaN,bank,...,NaN,91 Henry Brooklyn,NaN,50,91 Henry Brooklyn,NaN,NaN,NaN,NaN,1
19,19,19,BAIN ALEXANDER,ALEXANDER,BAIN,NaN,False,NaN,NaN,NaN,...,NaN,181 inventor,NaN,NaN,181 inventor,NaN,NaN,NaN,NaN,1
20,20,20,Baldwin Ezekiel,Ezekiel,Baldwin,NaN,False,NaN,NaN,shoemaker,...,NaN,79 Av B,NaN,NaN,79 Av B,NaN,NaN,NaN,NaN,1
21,21,21,Ball Isaac,Isaac,Ball,NaN,False,NaN,NaN,pedler,...,NaN,66 Mangin,NaN,NaN,66 Mangin,NaN,NaN,NaN,NaN,1
22,22,22,Bannon Michael,Michael,Bannon,NaN,False,NaN,NaN,cooper,...,NaN,304 Ninth,NaN,NaN,304 Ninth,NaN,NaN,NaN,NaN,1
23,23,23,Barmore Christopher,Christopher,Barmore,NaN,False,NaN,NaN,shoes,...,NaN,E 18th n Av A,NaN,NaN,E 18th n Av A,E 18th,Av A,NaN,NaN,0
24,24,24,Barratt Thomas,Thomas,Barratt,NaN,False,NaN,NaN,carman,...,NaN,605 Fourth,NaN,NaN,605 Fourth,NaN,NaN,NaN,NaN,1
25,25,25,"Barrowclough James , E",James,Barrowclough,",",False,NaN,NaN,NaN,...,NaN,24th c Av 3,NaN,NaN,24th c Av 3,NaN,NaN,24th,Av 3,0
26,26,26,Barry James,James,Barry,NaN,False,NaN,NaN,marblepolisher,...,NaN,294 Eleventh,NaN,NaN,294 Eleventh,NaN,NaN,NaN,NaN,1
27,27,27,Barry John,John,Barry,NaN,False,NaN,NaN,carpenter,...,NaN,60 Av C,NaN,NaN,60 Av C,NaN,NaN,NaN,NaN,1
28,28,28,Bates John C,John,Bates,C,False,NaN,NaN,sarsaparilla,...,NaN,Brooklyn,NaN,82,Brooklyn,NaN,NaN,NaN,NaN,1
29,29,29,Beach John T,John,Beach,T,False,NaN,NaN,paper,...,NaN,22 Vesey,NaN,43,22 Vesey,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80539,80539,112934,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,...,NaN,Montgomery,NaN,NaN,Montgomery,NaN,NaN,NaN,NaN,1
80540,80540,112937,ott -,-,ott,NaN,False,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,1
80541,80541,112940,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,...,NaN,Broome,NaN,NaN,Broome,NaN,NaN,NaN,NaN,1
80542,80542,112955,i,NaN,NaN,NaN,False,NaN,NaN,NaN,...,NaN,25t,NaN,NaN,25t,NaN,NaN,NaN,NaN,1
80543,80543,112961,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,...,NaN,Broadway,NaN,NaN,Broadway,NaN,NaN,NaN,NaN,1
80544,80544,112973,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,...,NaN,Dominick,NaN,NaN,Dominick,NaN,NaN,NaN,NaN,1
80545,80545,112981,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,...,NaN,Av 1,& 2,NaN,Av 1,NaN,NaN,NaN,NaN,1
80546,80546,112993,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,...,NaN,Williamsburg,NaN,NaN,Williamsburg,NaN,NaN,NaN,NaN,1
80547,80547,113004,Charles .,.,Charles,NaN,False,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,1
80548,80548,113007,Dedion â€”â€”,â€”â€”,Dedion,NaN,False,NaN,NaN,NaN,...,NaN,4 Depau row,NaN,NaN,4 Depau row,NaN,NaN,NaN,NaN,1
80549,80549,113015,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,...,NaN,DEG,NaN,NaN,DEG,NaN,NaN,NaN,NaN,1
80550,80550,113028,Deferusae â€”â€”,â€”â€”,Deferusae,NaN,False,NaN,NaN,NaN,...,NaN,69 Union pl,NaN,NaN,69 Union pl,NaN,NaN,NaN,NaN,1
80551,80551,113089,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,...,NaN,DEL,NaN,NaN,DEL,NaN,NaN,NaN,NaN,1
80552,80552,113217,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,...,NaN,6 St Mark s pl,NaN,NaN,6 St Mark s pl,NaN,NaN,NaN,NaN,1
80553,80553,113224,DELAVAN CHRISTIAN S,CHRISTIAN,DELAVAN,S,False,NaN,NaN,commission merchant,...,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,1
80554,80554,113234,DELAWARE & HUDSON CANAL COMPANY,&,DELAWARE,HUDSON,False,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,1
80555,80555,113239,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,...,NaN,rsley,NaN,NaN,rsley,NaN,NaN,NaN,NaN,1
80556,80556,113244,Greenwich .,.,Greenwich,NaN,False,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,1
80557,80557,113247,Bleecker |,|,Bleecker,NaN,False,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,1
80558,80558,113256,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,...,NaN,Brooklyn,NaN,NaN,Brooklyn,NaN,NaN,NaN,NaN,1
80559,80559,113261,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,...,NaN,and 250 Av 4,NaN,NaN,and 250 Av 4,NaN,NaN,NaN,NaN,1
80560,80560,113268,NaN,NaN,NaN,NaN,False,NaN,NaN,liam and hotel,...,NaN,25 Broadway,NaN,NaN,25 Broadway,NaN,NaN,NaN,NaN,1
80561,80561,113286,NaN,NaN,NaN,NaN,False,NaN,NaN,picture frames,...,NaN,Bway n W 28,NaN,495,Bway n W 28,Bway,W 28,NaN,NaN,0
80562,80562,113291,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,...,NaN,Washington a,NaN,NaN,Washington a,NaN,NaN,NaN,NaN,1
80563,80563,113309,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,...,NaN,Washington pl,NaN,NaN,Washington pl,NaN,NaN,NaN,NaN,1
80564,80564,113314,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,...,NaN,liamsburg,NaN,NaN,liamsburg,NaN,NaN,NaN,NaN,1
80565,80565,113320,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,...,NaN,Wil,NaN,NaN,Wil,NaN,NaN,NaN,NaN,1
80566,80566,113321,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,...,NaN,DEM,NaN,NaN,DEM,NaN,NaN,NaN,NaN,1
80567,80567,113401,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,...,NaN,DEN,NaN,NaN,DEN,NaN,NaN,NaN,NaN,1
80568,80568,113429,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,...,NaN,34th n Av 9,NaN,NaN,34th n Av 9,34th,Av 9,NaN,NaN,0

In [48]:
#df.to_excel('/Users/prajwal/Desktop/Columbia/C4SR/mn_1880/not so confident-mn1880-v7.xlsx')

In [49]:
df.to_excel('/Users/prajwal/Desktop/Columbia/C4SR/tesseract lib/mn 1850/data/mn-1850-2.xlsx')